"""Execute one immutable-assessment-authorized point forecast."""
from __future__ import annotations
import argparse, hashlib, json, math, shutil, sys, warnings
from datetime import datetime, timezone
from pathlib import Path
from typing import Any
import numpy as np
import pandas as pd
from sklearn.exceptions import ConvergenceWarning
from feature_engineering import FEATURE_COLUMNS, build_features, build_inference_features
from model_factory import build_candidate_estimator, canonical_sha256, load_and_validate_candidate_registry
from runtime_approved_forecast_commit import commit_approved_forecast
from runtime_commit import atomic_json, sha256_file
from runtime_context import require_absolute_directory, require_within
from runtime_validate import HORIZON_WEEKS, TARGET, compute_dataset_id

def _now():return datetime.now(timezone.utc).isoformat().replace("+00:00","Z")
def _json(path:Path)->dict[str,Any]:
    value=json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(value,dict):raise ValueError(f"{path.name} must be an object.")
    return value
def _period(y:int,w:int):return f"{y}-W{w:02d}"
def _advance(y:int,w:int,n:int):o=y*52+w-1+n;return o//52,o%52+1
def _update(path:Path,job:dict[str,Any],**changes):job.update(changes);job["updatedAt"]=_now();atomic_json(path,job)
def _write(path:Path,value:Any):atomic_json(path,value)

def execute(args:argparse.Namespace)->dict[str,Any]:
    root=require_absolute_directory(args.runtime_root,"runtime root");job_path=require_within(root,args.job_record,"job record");assessment=require_within(root,args.assessment,"assessment");staging=require_within(root,args.staging,"staging")
    job=_json(job_path)
    if job.get("jobKind")!="approved_forecast" or job.get("status")!="running" or job.get("workflowMode")!="approved_assessment_forecast" or staging.parent!=(root/"staging").resolve() or assessment.parent!=(root/"assessments").resolve():raise ValueError("The approved forecast job or paths are invalid.")
    _update(job_path,job,progress="verifying_decision");decision_root=require_within(root,root/"decisions"/job["decisionId"],"decision");decision=_json(decision_root/"decision.json")
    if sha256_file(decision_root/"commit.json")!=job["decisionCommitSha256"] or decision.get("authorizationId")!=job["authorizationId"] or decision.get("selectedModelId")!=job["selectedModelId"] or decision.get("selectedModelParameterSha256")!=job["selectedModelParameterSha256"] or not decision.get("forecastAuthorized"):raise ValueError("The immutable decision binding is invalid.")
    auth_root=require_within(root,root/"authorizations"/job["authorizationId"],"authorization");authorization=_json(auth_root/"authorization.json");auth_commit=_json(auth_root/"commit.json");reservation=_json(root/"authorization-state"/job["authorizationId"]/"reservation.json")
    if auth_commit.get("authorizationSha256")!=sha256_file(auth_root/"authorization.json") or authorization.get("decisionCommitSha256")!=job["decisionCommitSha256"] or reservation.get("jobId")!=job["jobId"] or reservation.get("runId")!=job["runId"]:raise ValueError("The one-run authorization is invalid.")
    _update(job_path,job,progress="verifying_assessment");assessment_commit_path=assessment/"metadata"/"commit.json"
    if sha256_file(assessment_commit_path)!=job["assessmentCommitSha256"]:raise ValueError("The immutable assessment commit changed.")
    assessment_commit=_json(assessment_commit_path);summary=_json(assessment/"artifacts"/"assessment_summary.json")
    if summary.get("assessmentId")!=job["assessmentId"] or summary.get("datasetId")!=job["datasetId"] or assessment_commit.get("artifactHashes",{}).get("assessment_summary.json")!=sha256_file(assessment/"artifacts"/"assessment_summary.json"):raise ValueError("The immutable assessment evidence is invalid.")
    candidate=next((c for c in summary["candidates"] if c["modelId"]==job["selectedModelId"]),None)
    if not candidate or candidate.get("deployabilityClass")!="deployable_learned_model" or candidate.get("completionStatus")!="complete" or not candidate.get("selectionEligible") or candidate.get("parametersSha256")!=job["selectedModelParameterSha256"]:raise ValueError("The selected model is not deployment-eligible assessment evidence.")
    canonical_case=assessment/"inputs"/"canonical"/"dengue_cases.csv";canonical_climate=assessment/"inputs"/"canonical"/"climate_data.csv";validation_path=assessment/"metadata"/"validation.json";validation=_json(validation_path)
    feature_hash=summary["provenance"]["featureOrderSha256"]
    if sha256_file(validation_path)!=job["validationRecordSha256"] or compute_dataset_id(canonical_case.read_bytes(),canonical_climate.read_bytes(),job["deploymentId"],feature_hash)!=job["datasetId"]:raise ValueError("Assessment input identity no longer matches the decision.")
    if staging.exists() and {p.name for p in staging.iterdir()}-{"logs"}:raise ValueError("Approved forecast staging contains unexpected content.")
    for relative in ("metadata","inputs/original","inputs/canonical","artifacts"):(staging/relative).mkdir(parents=True,exist_ok=False if relative=="metadata" else True)
    _update(job_path,job,progress="loading_immutable_inputs")
    for source,target in ((assessment/"inputs"/"original"/"dengue.csv",staging/"inputs"/"original"/"dengue.csv"),(assessment/"inputs"/"original"/"climate.csv",staging/"inputs"/"original"/"climate.csv"),(canonical_case,staging/"inputs"/"canonical"/"dengue_cases.csv"),(canonical_climate,staging/"inputs"/"canonical"/"climate_data.csv"),(validation_path,staging/"metadata"/"validation.json")):shutil.copy2(source,target)
    _update(job_path,job,progress="building_features");training,_=build_features(canonical_case,canonical_climate,output_path=None);inference=build_inference_features(canonical_case,canonical_climate)
    if len(training)!=173 or inference.empty or list(training[FEATURE_COLUMNS].columns)!=list(FEATURE_COLUMNS) or canonical_sha256(list(FEATURE_COLUMNS))!=feature_hash:raise ValueError("The governed full-training feature contract is unavailable.")
    X=training[FEATURE_COLUMNS].apply(pd.to_numeric,errors="raise");y=pd.to_numeric(training[TARGET],errors="raise");latest=inference.iloc[-1];x_latest=latest[FEATURE_COLUMNS].to_frame().T.astype(float)
    if not np.isfinite(X.to_numpy()).all() or not np.isfinite(y.to_numpy()).all() or (y<0).any() or not np.isfinite(x_latest.to_numpy()).all():raise ValueError("Approved forecast training data contains invalid values.")
    registry,registry_hash=load_and_validate_candidate_registry()
    if registry_hash!=summary["provenance"]["candidateRegistrySha256"]:raise ValueError("Candidate registry identity changed after assessment.")
    registry_candidate=next(c for c in registry["candidates"] if c["model_id"]==job["selectedModelId"])
    if registry_candidate["parameters_sha256"]!=job["selectedModelParameterSha256"]:raise ValueError("Selected-model parameter identity changed.")
    _update(job_path,job,progress="training_selected_model")
    with warnings.catch_warnings(record=True) as caught:
        warnings.simplefilter("always");estimator=build_candidate_estimator(job["selectedModelId"],registry);estimator.fit(X,y);raw=float(estimator.predict(x_latest)[0])
    if any(issubclass(w.category,ConvergenceWarning) for w in caught):raise ValueError("Selected model emitted an unresolved convergence warning.")
    if not math.isfinite(raw) or (job["selectedModelId"] in {"poisson_regression","random_forest"} and raw<0):raise ValueError("Selected model returned an invalid point forecast.")
    published=max(0.0,raw);reported=int(round(published));latest_cases=int(latest["cases"]);direction="Increasing" if reported>latest_cases else "Decreasing" if reported<latest_cases else "Stable";ty,tw=_advance(int(latest["epi_year"]),int(latest["epi_week"]),HORIZON_WEEKS);target_period=_period(ty,tw);generated=_now()
    feature_bytes=training.to_csv(index=False,lineterminator="\n").encode();feature_matrix_hash=hashlib.sha256(feature_bytes).hexdigest();training_identity={"datasetId":job["datasetId"],"featureMatrixSha256":feature_matrix_hash,"trainingRowCount":173,"trainingPeriod":{"start":_period(int(training.iloc[0]["epi_year"]),int(training.iloc[0]["epi_week"])),"end":_period(int(training.iloc[-1]["epi_year"]),int(training.iloc[-1]["epi_week"]))},"featureOrderSha256":feature_hash,"library":"scikit-learn"}
    artifacts=staging/"artifacts";(artifacts/"model_features.csv").write_bytes(feature_bytes);_write(artifacts/"input_manifest.json",{"schemaVersion":"1.0","runId":job["runId"],"assessmentId":job["assessmentId"],"datasetId":job["datasetId"],"validationRecordSha256":job["validationRecordSha256"],"canonicalDengueSha256":sha256_file(canonical_case),"canonicalClimateSha256":sha256_file(canonical_climate),"featureOrderSha256":feature_hash,"generatedAt":generated})
    _update(job_path,job,progress="generating_point_forecast");forecast={"schemaVersion":"1.0","runId":job["runId"],"jobId":job["jobId"],"datasetId":job["datasetId"],"deploymentId":job["deploymentId"],"sourceType":"uploaded","workflowMode":"approved_assessment_forecast","decisionId":job["decisionId"],"assessmentId":job["assessmentId"],"authorizationId":job["authorizationId"],"selectedModelId":job["selectedModelId"],"selectedModelParameterSha256":job["selectedModelParameterSha256"],"technicalWinnerModelId":decision["technicalWinnerModelId"],"decisionOutcome":decision["decision"],"selectionBasis":"immutable_dataset_assessment_and_internal_one_run_decision","comparisonPerformed":True,"recommendationStrength":"not_available","decisionScope":"one_run","deploymentModelAdopted":False,"trainingDataIdentity":training_identity,"latestObservedCases":latest_cases,"forecastRaw":raw,"forecastReported":reported,"targetPeriod":target_period,"target":TARGET,"horizonWeeks":2,"forecastGrowthCategory":direction,"reportingRoundingPolicy":"nearest_integer_python_round_half_to_even","clippingApplied":raw!=published,"generatedAt":generated,"uncertaintyStatus":"pending_selected_model_calibration","preparednessStatus":"unavailable_missing_planning_policy"};_write(artifacts/"forecast_output.json",forecast)
    uncertainty={"schemaVersion":"1.0","runId":job["runId"],"jobId":job["jobId"],"datasetId":job["datasetId"],"deploymentId":job["deploymentId"],"decisionId":job["decisionId"],"assessmentId":job["assessmentId"],"selectedModelId":job["selectedModelId"],"selectedModelParameterSha256":job["selectedModelParameterSha256"],"uncertaintyStatus":"pending_selected_model_calibration","lowerRaw":None,"upperRaw":None,"lowerReported":None,"upperReported":None,"nominalCoverage":None,"historicalCoverage":None,"calibrationMethod":None,"residualCount":None,"isPredictionInterval":False,"calibratedOnSyntheticData":False,"rmseFallbackAllowed":False,"bundledP13RangeReused":False,"syntheticRangeReused":False,"limitations":["Selected-model calibration has not been governed or executed.","Assessment residuals are retained as evidence but no interval is inferred from them."],"generatedAt":generated};_write(artifacts/"forecast_uncertainty.json",uncertainty)
    cases=pd.read_csv(canonical_case);history=[{"period":_period(int(r.epi_year),int(r.epi_week)),"cases":int(r.cases)} for r in cases.tail(52).itertuples()];_write(artifacts/"chart_data.json",{"schemaVersion":"1.0","runId":job["runId"],"history":history,"forecast":{"period":target_period,"cases":reported},"empiricalRange":None})
    dashboard={"schemaVersion":"1.0","run":{"runId":job["runId"],"jobId":job["jobId"],"datasetId":job["datasetId"],"deploymentId":job["deploymentId"],"workflowMode":"approved_assessment_forecast","sourceType":"uploaded","committedAt":generated,"completedSteps":7},"model":{"modelId":job["selectedModelId"],"modelLabel":registry_candidate["model_family"],"parameterHash":job["selectedModelParameterSha256"],"technicalWinnerModelId":decision["technicalWinnerModelId"],"selectionBasis":"immutable_dataset_assessment_and_internal_one_run_decision","comparisonPerformed":True,"deploymentModelAdopted":False},"decision":{"decisionId":job["decisionId"],"assessmentId":job["assessmentId"],"authorizationId":job["authorizationId"],"outcome":decision["decision"],"scope":"one_run","operatorType":"trusted_internal_unverified","institutionalApproval":False},"forecast":{"latestObservedCases":latest_cases,"forecastRaw":raw,"forecastReported":reported,"targetPeriod":target_period,"target":TARGET,"horizonWeeks":2,"direction":direction,"uncertaintyStatus":"pending_selected_model_calibration","empiricalLower":None,"empiricalUpper":None},"history":history,"preparedness":{"availabilityStatus":"unavailable_missing_planning_policy","scenarios":None,"counts":None,"facilities":[],"alerts":[]},"evidence":{"validation":{"sha256":job["validationRecordSha256"],"acceptedPeriod":validation.get("acceptedPeriod")},"assessment":{"assessmentId":job["assessmentId"],"commitSha256":job["assessmentCommitSha256"]},"decision":{"decisionId":job["decisionId"],"commitSha256":job["decisionCommitSha256"]},"modelCard":{"path":"artifacts/model_card.json"},"provenance":{"datasetId":job["datasetId"],"inputManifest":"artifacts/input_manifest.json"}},"limitations":["Technical evidence only; recommendation strength is not available.","The trusted internal operator identity is not verified.","This decision authorizes one run and does not adopt a deployment model.","Uncertainty and preparedness are unavailable."]};_write(artifacts/"dashboard_summary.json",dashboard)
    _write(artifacts/"pipeline_run_summary.json",{"schemaVersion":"1.0","runId":job["runId"],"jobId":job["jobId"],"status":"commit_ready","steps":["decision_verified","assessment_verified","features_built","selected_model_trained","point_forecast_generated","artifacts_validated"],"candidateComparisonPerformed":True,"candidateComparisonExecutedInThisRun":False,"uncertaintyCalibrationPerformed":False,"operationalEngineExecuted":False,"generatedAt":generated})
    sequence=["input_manifest.json","model_features.csv","forecast_output.json","forecast_uncertainty.json","chart_data.json","dashboard_summary.json","pipeline_run_summary.json","model_card.json"];run={"schemaVersion":"1.0","runId":job["runId"],"jobId":job["jobId"],"datasetId":job["datasetId"],"deploymentId":job["deploymentId"],"workflowMode":"approved_assessment_forecast","sourceType":"uploaded","status":"commit_ready","decisionId":job["decisionId"],"assessmentId":job["assessmentId"],"authorizationId":job["authorizationId"],"selectedModelId":job["selectedModelId"],"selectedModelParameterSha256":job["selectedModelParameterSha256"],"decisionScope":"one_run","deploymentModelAdopted":False,"createdAt":job["createdAt"],"generatedAt":generated,"artifactPublicationSequence":sequence};_write(staging/"metadata"/"run.json",run)
    hashes={name:sha256_file(artifacts/name) for name in sequence if name!="model_card.json"};card={"schemaVersion":"1.0","runId":job["runId"],"jobId":job["jobId"],"datasetId":job["datasetId"],"deploymentId":job["deploymentId"],"workflowMode":"approved_assessment_forecast","sourceType":"uploaded","decision":{"id":job["decisionId"],"commitSha256":job["decisionCommitSha256"],"outcome":decision["decision"],"operatorType":"trusted_internal_unverified"},"assessment":{"id":job["assessmentId"],"commitSha256":job["assessmentCommitSha256"],"foldCount":68,"recommendationStrength":"not_available"},"authorization":{"id":job["authorizationId"],"scope":"one_run"},"model":{"id":job["selectedModelId"],"family":registry_candidate["model_family"],"parameterHash":job["selectedModelParameterSha256"],"candidateRegistrySha256":registry_hash,"runtimeLibrary":"scikit-learn"},"features":{"count":18,"orderSha256":feature_hash},"target":TARGET,"horizonWeeks":2,"training":training_identity,"comparisonPerformed":True,"recommendationStrength":"not_available","decisionScope":"one_run","deploymentModelAdopted":False,"operatorType":"trusted_internal_unverified","institutionalApproval":False,"uncertaintyStatus":"pending_selected_model_calibration","preparednessStatus":"unavailable_missing_planning_policy","inputHashes":{"canonicalDengue":sha256_file(canonical_case),"canonicalClimate":sha256_file(canonical_climate),"assessmentCommit":job["assessmentCommitSha256"],"decisionCommit":job["decisionCommitSha256"]},"artifactHashes":hashes,"commitReadiness":"ready_for_runtime_commit","intendedUse":"Model selected through a trusted internal decision bound to immutable dataset-specific assessment evidence for one forecast run.","limitations":["Technical comparison was performed on 68 governed temporal folds.","Recommendation strength was not governed.","This decision authorizes one forecast run only.","This does not constitute deployment-wide model adoption.","Operator identity and institutional approval are not verified.","Uncertainty calibration has not been completed and preparedness is unavailable."],"generatedAt":_now()}
    _update(job_path,job,progress="validating_artifacts");_write(artifacts/"model_card.json",card);(staging/"logs"/"events.jsonl").write_text(json.dumps({"timestamp":_now(),"eventType":"approved_forecast_artifacts_ready","runId":job["runId"]})+"\n",encoding="utf-8");_update(job_path,job,status="committing",progress="committing_run");committed=commit_approved_forecast(root,staging,job);return {"runId":job["runId"],"forecastReported":reported,"latest":committed["pointer"]}

def main():
    p=argparse.ArgumentParser();p.add_argument("--runtime-root",required=True);p.add_argument("--job-record",required=True);p.add_argument("--assessment",required=True);p.add_argument("--staging",required=True);args=p.parse_args()
    try:print(json.dumps(execute(args),separators=(",",":")));return 0
    except Exception as exc:print(json.dumps({"ok":False,"code":"approved_forecast_failed","message":str(exc)}),file=sys.stderr);return 1
if __name__=="__main__":raise SystemExit(main())
