import json
import shutil
import sys
import uuid
from datetime import datetime, timedelta, timezone
from pathlib import Path
from types import SimpleNamespace

ROOT=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(ROOT/"analytics"))

from runtime_commit import atomic_json, sha256_file
from runtime_worker import run_once
from runtime_forecast_outcome import execute as execute_outcome
from runtime_model_degradation_evidence import execute as execute_degradation
from runtime_assessment_evidence import aggregate_candidate,select_technical_winner
from tests.test_runtime_assessment_commit import build_ready_assessment_runtime, iso_now
from tests.test_runtime_forecast_outcome import build_outcome_job
from tests.test_runtime_model_degradation_evidence import degradation_job


def build_promotion_chain(base: Path, repository_root: Path, model_id: str = "random_forest") -> dict:
    base_runtime, _workspace, _pending, assessment_job = build_ready_assessment_runtime(base/"base")
    if not run_once(base_runtime, "lifecycle-assessment"): raise AssertionError("assessment did not execute")
    runtime=(base/model_id/"runtime").resolve();shutil.copytree(base_runtime,runtime,copy_function=shutil.copyfile)
    assessment = runtime / "assessments" / assessment_job["assessmentId"]
    summary_path=assessment/"artifacts/assessment_summary.json"; comparison_path=assessment/"artifacts/candidate_model_comparison.json"; rolling_path=assessment/"artifacts/rolling_validation.json";recommendation_path=assessment/"artifacts/recommendation.json";metadata_path=assessment/"metadata/assessment.json";commit_path=assessment/"metadata/commit.json"
    summary=json.loads(summary_path.read_text());comparison=json.loads(comparison_path.read_text());rolling=json.loads(rolling_path.read_text());recommendation=json.loads(recommendation_path.read_text());metadata=json.loads(metadata_path.read_text());selected=next(candidate for candidate in summary["candidates"] if candidate["modelId"]==model_id)
    if model_id!="random_forest":
        for fold in rolling["folds"]:
            chosen=next(value for value in fold["predictions"] if value["modelId"]==model_id);forest=next(value for value in fold["predictions"] if value["modelId"]=="random_forest");chosen["modelId"],forest["modelId"]="random_forest",model_id
        actuals=[fold["actualTarget"] for fold in rolling["folds"]];records={candidate["modelId"]:[next(value for value in fold["predictions"] if value["modelId"]==candidate["modelId"]) for fold in rolling["folds"]] for candidate in comparison["candidates"]}
        for candidate in comparison["candidates"]:candidate["metrics"]=aggregate_candidate(records[candidate["modelId"]],actuals)
        winner,tie_stage,tie_steps,eligible_ids=select_technical_winner(comparison["candidates"]);assert winner==model_id
        winner_records=records[winner]
        for candidate in comparison["candidates"]:
            better=tied=worse=0
            for record,chosen_record in zip(records[candidate["modelId"]],winner_records):
                difference=record["absoluteError"]-chosen_record["absoluteError"];better+=difference < -1e-9;tied+=abs(difference)<=1e-9;worse+=difference>1e-9
            candidate["foldWinsTiesLosses"]={"better":better,"tied":tied,"worse":worse}
        comparison.update(technicalWinnerModelId=winner,winnerParameterSha256=selected["parametersSha256"],tieStage=tie_stage,tieResolutionSteps=tie_steps,selectionEligibleCandidateIds=eligible_ids,selectionReason=f"{winner} had the lowest governed metric sequence among candidates completing all {len(rolling['folds'])} folds.")
        winner_candidate=next(value for value in comparison["candidates"] if value["modelId"]==winner);runner=min((value for value in comparison["candidates"] if value["modelId"]!=winner),key=lambda value:value["metrics"]["mae"]);winner_mae=winner_candidate["metrics"]["mae"];runner_mae=runner["metrics"]["mae"]
        recommendation.update(technicalWinnerModelId=winner,winnerParameterSha256=winner_candidate["parametersSha256"],evidenceInputs={"winnerMae":winner_mae,"runnerUpMae":runner_mae,"absoluteMaeGap":runner_mae-winner_mae,"relativeMaeGap":(runner_mae-winner_mae)/runner_mae,"successfulFoldRatio":1.0,"failedFoldCount":0,"clippingCount":winner_candidate["metrics"]["clippingCount"],"warningCount":winner_candidate["metrics"]["warningCount"],"candidateBreadth":len(comparison["candidates"]),"tieBreakStageUsed":tie_stage,"datasetFoldCount":len(rolling["folds"])})
        atomic_json(rolling_path,rolling)
        comparison["rollingValidationSha256"]=sha256_file(rolling_path)
    comparison["technicalWinnerModelId"]=model_id;comparison["winnerParameterSha256"]=selected["parametersSha256"];summary["technicalWinnerModelId"]=model_id;summary["candidates"]=comparison["candidates"];summary["selectionReason"]=comparison["selectionReason"];summary["tieStage"]=comparison["tieStage"]
    atomic_json(comparison_path,comparison);atomic_json(recommendation_path,recommendation);summary["evidenceHashes"]["rollingValidationSha256"]=sha256_file(rolling_path);summary["evidenceHashes"]["candidateComparisonSha256"]=sha256_file(comparison_path);summary["evidenceHashes"]["recommendationSha256"]=sha256_file(recommendation_path);atomic_json(summary_path,summary)
    metadata["artifactHashes"]["rollingValidationSha256"]=sha256_file(rolling_path);metadata["artifactHashes"]["candidateComparisonSha256"]=sha256_file(comparison_path);metadata["artifactHashes"]["recommendationSha256"]=sha256_file(recommendation_path);metadata["artifactHashes"]["assessmentSummarySha256"]=sha256_file(summary_path);atomic_json(metadata_path,metadata)
    assessment_commit=json.loads(commit_path.read_text());assessment_commit["artifactHashes"]["rolling_validation.json"]=sha256_file(rolling_path);assessment_commit["artifactHashes"]["candidate_model_comparison.json"]=sha256_file(comparison_path);assessment_commit["artifactHashes"]["recommendation.json"]=sha256_file(recommendation_path);assessment_commit["artifactHashes"]["assessment_summary.json"]=sha256_file(summary_path);atomic_json(commit_path,assessment_commit)
    assessment_commit_sha=sha256_file(commit_path);decision_id,authorization_id,job_id,run_id=[str(uuid.uuid4()) for _ in range(4)];created=iso_now();expires=(datetime.now(timezone.utc)+timedelta(hours=1)).isoformat().replace("+00:00","Z")
    policy=json.loads((repository_root/"config/deployments/dhaka_south/decision_policy.json").read_text());decision_root=runtime/"decisions"/decision_id;decision_root.mkdir(parents=True)
    decision={"schemaVersion":"2.0","decisionId":decision_id,"assessmentId":assessment_job["assessmentId"],"assessmentCommitSha256":assessment_commit_sha,"datasetId":summary["datasetId"],"assessmentSchemaVersion":"2.0","assessmentLabelledRows":summary["labelledRows"],"assessmentPlannedFoldCount":summary["foldPolicy"]["plannedFoldCount"],"selectedEvaluationPeriod":summary["foldPolicy"]["selectedEvaluationPeriod"],"assessmentSummarySha256":sha256_file(summary_path),"comparisonSha256":sha256_file(comparison_path),"recommendationSha256":summary["evidenceHashes"]["recommendationSha256"],"foldPlanSha256":summary["foldPlanSha256"],"deploymentId":"dhaka_south","validationRecordSha256":summary["provenance"]["validationRecordSha256"],"assessmentPolicyId":policy["allowedAssessmentPolicyId"],"assessmentPolicyVersion":policy["allowedAssessmentPolicyVersion"],"assessmentPolicySha256":policy["allowedAssessmentPolicySha256"],"decisionPolicyId":policy["policyId"],"decisionPolicyVersion":policy["policyVersion"],"decisionPolicySha256":policy["policySha256"],"candidateRegistrySha256":policy["candidateRegistrySha256"],"technicalWinnerModelId":model_id,"technicalWinnerParameterSha256":selected["parametersSha256"],"decision":"approve_technical_winner","selectedModelId":model_id,"selectedModelParameterSha256":selected["parametersSha256"],"decisionScope":"one_run","operatorType":"trusted_internal_unverified","operatorIdentifier":"lifecycle-fixture","institutionalApproval":False,"reason":"Governed lifecycle fixture.","limitationsAcknowledged":True,"decisionStatus":"approved_technical_winner","forecastAuthorized":True,"authorizationId":authorization_id,"createdAt":created,"correlationId":str(uuid.uuid4()),"supersedesDecisionId":None,"supersessionStatus":"active"}
    atomic_json(decision_root/"decision.json",decision)
    decision_commit={"schemaVersion":"2.0","decisionId":decision_id,"assessmentId":assessment_job["assessmentId"],"decisionSha256":sha256_file(decision_root/"decision.json"),"assessmentCommitSha256":assessment_commit_sha,"assessmentSchemaVersion":"2.0","assessmentSummarySha256":sha256_file(summary_path),"assessmentPolicyId":policy["allowedAssessmentPolicyId"],"assessmentPolicyVersion":policy["allowedAssessmentPolicyVersion"],"assessmentPolicySha256":policy["allowedAssessmentPolicySha256"],"decisionPolicyId":policy["policyId"],"decisionPolicyVersion":policy["policyVersion"],"decisionPolicySha256":policy["policySha256"],"foldPlanSha256":summary["foldPlanSha256"],"assessmentLabelledRows":summary["labelledRows"],"assessmentPlannedFoldCount":summary["foldPolicy"]["plannedFoldCount"],"status":"committed","committedAt":created,"latestPointerUpdated":False,"deploymentProfileModified":False}
    atomic_json(decision_root/"commit.json",decision_commit);decision_commit_sha=sha256_file(decision_root/"commit.json")
    auth_root=runtime/"authorizations"/authorization_id;auth_root.mkdir(parents=True)
    authorization={"schemaVersion":"2.0","authorizationId":authorization_id,"decisionId":decision_id,"decisionCommitSha256":decision_commit_sha,"assessmentId":assessment_job["assessmentId"],"assessmentCommitSha256":assessment_commit_sha,"assessmentPolicyId":policy["allowedAssessmentPolicyId"],"assessmentPolicyVersion":policy["allowedAssessmentPolicyVersion"],"assessmentPolicySha256":policy["allowedAssessmentPolicySha256"],"decisionPolicyId":policy["policyId"],"decisionPolicyVersion":policy["policyVersion"],"decisionPolicySha256":policy["policySha256"],"datasetId":summary["datasetId"],"deploymentId":"dhaka_south","selectedModelId":model_id,"selectedModelParameterSha256":selected["parametersSha256"],"assessmentLabelledRows":summary["labelledRows"],"assessmentPlannedFoldCount":summary["foldPolicy"]["plannedFoldCount"],"foldPlanSha256":summary["foldPlanSha256"],"workflowMode":"approved_assessment_forecast","scope":"one_run","initialStatus":"available","createdAt":created,"expiresAt":expires,"policyId":policy["policyId"],"policyVersion":policy["policyVersion"],"policySha256":policy["policySha256"]}
    atomic_json(auth_root/"authorization.json",authorization);atomic_json(auth_root/"commit.json",{"schemaVersion":"1.0","authorizationId":authorization_id,"decisionId":decision_id,"authorizationSha256":sha256_file(auth_root/"authorization.json"),"decisionCommitSha256":decision_commit_sha,"status":"committed","committedAt":created});authorization_commit_sha=sha256_file(auth_root/"commit.json")
    state=runtime/"authorization-state"/authorization_id;state.mkdir(parents=True);atomic_json(state/"reservation.json",{"schemaVersion":"1.0","authorizationId":authorization_id,"decisionId":decision_id,"eventType":"reserved","eventId":str(uuid.uuid4()),"createdAt":created,"jobId":job_id,"runId":run_id})
    job={"schemaVersion":"1.0","jobKind":"approved_forecast","jobId":job_id,"runId":run_id,"decisionId":decision_id,"decisionCommitSha256":decision_commit_sha,"authorizationId":authorization_id,"assessmentId":assessment_job["assessmentId"],"assessmentCommitSha256":assessment_commit_sha,"workspaceId":assessment_job["assessmentId"],"datasetId":summary["datasetId"],"deploymentId":"dhaka_south","selectedModelId":model_id,"selectedModelParameterSha256":selected["parametersSha256"],"workflowMode":"approved_assessment_forecast","validationRecordSha256":summary["provenance"]["validationRecordSha256"],"status":"queued","progress":"queued","createdAt":created,"claimedAt":None,"startedAt":None,"updatedAt":created,"completedAt":None,"heartbeatAt":None,"workerId":None,"processId":None,"timeoutSeconds":600,"retryCount":0,"error":None,"committedRunId":None}
    atomic_json(runtime/"jobs/pending"/f"{job_id}.json",job)
    if not run_once(runtime,"lifecycle-approved"):raise AssertionError("approved forecast did not execute")
    approved_commit_sha=sha256_file(runtime/"runs"/run_id/"metadata/commit.json")
    outcome_job,outcome_path=build_outcome_job(runtime,{"runId":run_id},record_id=f"lifecycle-{model_id}");execute_outcome(SimpleNamespace(runtime_root=str(runtime),job_record=str(outcome_path),staging=str(runtime/"outcome-staging"/outcome_job["outcomeId"])))
    outcome_commit_sha=sha256_file(runtime/"forecast-outcomes"/outcome_job["outcomeId"]/"metadata/commit.json");monitoring_latest=runtime/"deployments/dhaka_south/monitoring/latest.json";monitoring=json.loads(monitoring_latest.read_text());monitoring_summary=runtime/monitoring["monitoringSummaryPath"]
    degradation,degradation_path=degradation_job(runtime);execute_degradation(SimpleNamespace(runtime_root=str(runtime),job_record=str(degradation_path),staging=str(runtime/"degradation-staging"/degradation["evidenceId"])))
    degradation_latest=runtime/"deployments/dhaka_south/degradation/latest.json";degradation_pointer=json.loads(degradation_latest.read_text());degradation_evidence=runtime/degradation_pointer["evidencePath"]
    return {"runtime":runtime,"assessmentId":assessment_job["assessmentId"],"decisionId":decision_id,"authorizationId":authorization_id,"runId":run_id,"outcomeId":outcome_job["outcomeId"],"modelId":model_id,"assessmentCommitSha256":assessment_commit_sha,"decisionCommitSha256":decision_commit_sha,"authorizationCommitSha256":authorization_commit_sha,"approvedForecastCommitSha256":approved_commit_sha,"outcomeCommitSha256":outcome_commit_sha,"monitoringLatestSha256":sha256_file(monitoring_latest),"monitoringSummarySha256":sha256_file(monitoring_summary),"monitoringIncludedOutcomeSetSha256":json.loads(monitoring_summary.read_text())["outcomeSetSha256"],"degradationLatestSha256":sha256_file(degradation_latest),"degradationEvidenceCommitSha256":degradation_pointer["commitSha256"],"degradationEvidenceSha256":sha256_file(degradation_evidence)}
