import test from "node:test";import assert from "node:assert/strict";import{readFile}from"node:fs/promises";const read=p=>readFile(new URL(`../${p}`,import.meta.url),"utf8");
test("decision route is Node-only, constant-time protected, and rejects client model selection",async()=>{const s=await read("app/api/runtime/assessments/[assessmentId]/decisions/route.ts");assert.match(s,/runtime = "nodejs"/);assert.match(s,/timingSafeEqual/);assert.match(s,/internalDecisionEnabled/);assert.doesNotMatch(s,/selectedModelId:\s*body|selectedModelParameterSha256:\s*body/)});
test("approved forecast start accepts only a decision commit and reserves authorization",async()=>{const s=await read("app/api/runtime/decisions/[decisionId]/forecast/route.ts");assert.match(s,/expectedDecisionCommitSha256/);assert.match(s,/reservation/);assert.match(s,/approved_forecast/);assert.doesNotMatch(s,/modelId:\s*body|parameters:\s*body/)});
test("authorization remains one-run, expiry-checked, and never released by failed execution",async()=>{const route=await read("app/api/runtime/decisions/[decisionId]/forecast/route.ts");const store=await read("lib/runtime/decision-store.ts");const commit=await read("analytics/runtime_approved_forecast_commit.py");assert.match(route,/forecast_authorization_expired/);assert.match(route,/auth\.reservation/);assert.match(route,/already being reserved/);assert.doesNotMatch(route,/unlink\([^)]*reservation|releaseAuthorization|automaticRetry/i);assert.match(store,/authorizationCommitSha256/);assert.match(store,/authorization_integrity_error/);assert.match(commit,/latest\.json/);assert.match(commit,/consumption\.json/);assert.ok(commit.lastIndexOf('latest.json')<commit.lastIndexOf('consumption.json'))});
test("protected decision secret is confined to server routes",async()=>{for(const file of ["components/forecast/ForecastRunWorkflow.tsx","components/validation/RuntimeAssessmentWorkflow.tsx","lib/runtime/client.ts"]){const source=await read(file);assert.doesNotMatch(source,/x-dengueops-internal-decision-secret|internalDecisionSecret/)}});
test("frontend refreshes approved forecast only after committed run verification",async()=>{const s=await read("components/forecast/ForecastRunWorkflow.tsx");const branch=s.slice(s.indexOf("const runApprovedForecast"),s.indexOf("return <div"));assert.match(branch,/committedRunId/);assert.match(branch,/getLatestDashboard/);assert.match(branch,/latest\.runId/);assert.match(branch,/location\.assign/)});
test("assessment-centric decision lookup verifies the active index and redacts internals",async()=>{const s=await read("lib/runtime/decision-store.ts");const branch=s.slice(s.indexOf("export async function readVerifiedAssessmentDecisionState"));assert.match(branch,/assessmentDecisionPaths/);assert.match(branch,/readVerifiedDecision/);assert.match(branch,/decisionCommitSha256/);assert.match(branch,/assessmentId/);assert.doesNotMatch(branch,/operatorIdentifier|internalDecisionSecret|reason:/)});
test("baseline technical winners are never silently substituted",async()=>{const s=await read("lib/runtime/decision-store.ts");assert.match(s,/DEPLOYABLE/);assert.match(s,/selected_model_not_deployable/);assert.doesNotMatch(s,/runner.?up|fallbackModel|fallback_model/i)});
test("Phase 2 assessments cannot enter the Phase 1 decision policy",async()=>{const s=await read("lib/runtime/decision-store.ts");assert.match(s,/evidence\.commit\.assessmentPolicySha256/);assert.match(s,/policy\.allowedAssessmentPolicySha256/);assert.match(s,/decision_policy_mismatch/)});
