import test from "node:test";
import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import {mkdtemp,readdir,rm} from "node:fs/promises";
import {tmpdir} from "node:os";
import path from "node:path";
import {spawn} from "node:child_process";
import net from "node:net";
const read=path=>readFile(new URL(`../${path}`,import.meta.url),"utf8");

test("lifecycle route uses its distinct server-only credential and server operator",async()=>{const route=await read("app/api/runtime/model-lifecycle/route.ts"),config=await read("lib/runtime/config.ts");assert.match(route,/internalModelLifecycleSecret/);assert.match(route,/timingSafeEqual/);assert.match(route,/internalModelLifecycleOperatorId/);assert.doesNotMatch(route,/internalDecisionSecret|internalMonitoringSecret/);assert.match(config,/DENGUEOPS_INTERNAL_MODEL_LIFECYCLE_SECRET/);assert.match(config,/DENGUEOPS_INTERNAL_MODEL_LIFECYCLE_OPERATOR_ID/)});
test("lifecycle action bodies are explicit and reject client-selected authority",async()=>{const route=await read("app/api/runtime/model-lifecycle/route.ts");assert.match(route,/promotionHashes/);assert.match(route,/contextHashes/);assert.match(route,/exactKeys/);assert.match(route,/unexpected_model_lifecycle_field/);assert.doesNotMatch(route,/modelId:body|parameterSha256:body|rollbackTarget|threshold|outcomeExclusions/)});
test("browser client exposes lifecycle GET only",async()=>{const client=await read("lib/runtime/client.ts"),branch=client.slice(client.indexOf("getModelLifecycle"));assert.match(branch,/getModelLifecycle/);assert.doesNotMatch(branch,/postModelLifecycle|startModelLifecycle|recordLifecycle|x-dengueops-model-lifecycle-secret|method:\s*["']POST/)});
test("lifecycle GET is no-store and POST returns redacted job metadata",async()=>{const route=await read("app/api/runtime/model-lifecycle/route.ts");assert.match(route,/Cache-Control":"no-store/);assert.match(route,/statusUrl/);assert.doesNotMatch(route,/Response\.json\(\{ok:true,operatorIdentifier/)});

const secret="lifecycle-functional-secret-123";
const body={deployment:"dhaka_south",action:"bootstrap_historical_profile",expectedAssignmentPointerState:"absent",expectedAssignmentPointerSha256:null,expectedProfileSha256:"53fe1fb09aea994c34a5b3d6839b60092c777030445b8ec46c32520675a7233a",reason:"Isolated functional route test.",manualActionAcknowledged:true,statisticalSufficiencyNotGovernedAcknowledged:true,materialWorseningNotClassifiedAcknowledged:true,evidenceDoesNotProveSuperiorityAcknowledged:true,quickCompatibleRandomForestOnlyAcknowledged:true};
async function freePort(){return await new Promise((resolve,reject)=>{const server=net.createServer();server.listen(0,"127.0.0.1",()=>{const address=server.address();server.close(()=>resolve(address.port))});server.on("error",reject)})}
async function server(enabled,overrides={}){const runtime=await mkdtemp(path.join(tmpdir(),"dengueops-lifecycle-route-")),port=await freePort(),child=spawn(process.execPath,[path.join(process.cwd(),"node_modules/next/dist/bin/next"),"dev","-H","127.0.0.1","-p",String(port)],{cwd:process.cwd(),env:{...process.env,DENGUEOPS_RUNTIME_ROOT:runtime,DENGUEOPS_INTERNAL_DECISION_ENABLED:"false",DENGUEOPS_INTERNAL_DECISION_SECRET:"",DENGUEOPS_INTERNAL_MONITORING_ENABLED:"false",DENGUEOPS_INTERNAL_MONITORING_SECRET:"",DENGUEOPS_INTERNAL_MODEL_LIFECYCLE_ENABLED:String(enabled),DENGUEOPS_INTERNAL_MODEL_LIFECYCLE_SECRET:secret,DENGUEOPS_INTERNAL_MODEL_LIFECYCLE_OPERATOR_ID:"functional-route-operator",...overrides},stdio:["ignore","pipe","pipe"]});let stdout="",stderr="";child.stdout.on("data",value=>stdout+=value);child.stderr.on("data",value=>stderr+=value);const url=`http://127.0.0.1:${port}`;for(let attempt=0;attempt<80;attempt++){try{const res=await fetch(`${url}/api/runtime/model-lifecycle`);if(res.status===200||res.status===503){return{runtime,url,child,logs:()=>({stdout,stderr})}}}catch{}await new Promise(resolve=>setTimeout(resolve,100))}child.kill();await rm(runtime,{recursive:true,force:true});throw new Error("Next lifecycle test server did not start")}

async function stop(value){value.child.kill();await new Promise(resolve=>setTimeout(resolve,200));await rm(value.runtime,{recursive:true,force:true})}
test("functional lifecycle ingress enforces the distinct credential and server-derived operator",{timeout:30000},async()=>{const instance=await server(true);try{const get=await fetch(`${instance.url}/api/runtime/model-lifecycle`);assert.equal(get.status,200);assert.match(get.headers.get("cache-control")??"",/no-store/);assert.equal((await get.json()).authority.authoritySource,"historical_profile_fallback_pending_explicit_bootstrap");for(const wrong of ["wrong-secret","decision-secret-value","monitoring-secret-value"]){const response=await fetch(`${instance.url}/api/runtime/model-lifecycle`,{method:"POST",headers:{"content-type":"application/json","x-dengueops-model-lifecycle-secret":wrong},body:JSON.stringify(body)});assert.equal(response.status,401)}const accepted=await fetch(`${instance.url}/api/runtime/model-lifecycle`,{method:"POST",headers:{"content-type":"application/json","x-dengueops-model-lifecycle-secret":secret},body:JSON.stringify(body)});assert.equal(accepted.status,202);const jobs=await readdir(path.join(instance.runtime,"jobs/pending"));assert.equal(jobs.length,1);const job=JSON.parse(await readFile(path.join(instance.runtime,"jobs/pending",jobs[0]),"utf8"));assert.equal(job.operatorIdentifier,"functional-route-operator");assert.equal("modelId" in job,false);const arbitrary=await fetch(`${instance.url}/api/runtime/model-lifecycle`,{method:"POST",headers:{"content-type":"application/json","x-dengueops-model-lifecycle-secret":secret},body:JSON.stringify({...body,modelId:"ridge_regression"})});assert.equal(arbitrary.status,400);const rollbackTarget=await fetch(`${instance.url}/api/runtime/model-lifecycle`,{method:"POST",headers:{"content-type":"application/json","x-dengueops-model-lifecycle-secret":secret},body:JSON.stringify({...body,rollbackTarget:"arbitrary"})});assert.equal(rollbackTarget.status,400);await assert.rejects(readFile(path.join(instance.runtime,"deployments/dhaka_south/model-assignment/latest.json")))}finally{await stop(instance)}});
test("functional lifecycle ingress fails closed while disabled",{timeout:30000},async()=>{const instance=await server(false);try{const response=await fetch(`${instance.url}/api/runtime/model-lifecycle`,{method:"POST",headers:{"content-type":"application/json","x-dengueops-model-lifecycle-secret":secret},body:JSON.stringify(body)});assert.equal(response.status,503)}finally{await stop(instance)}});
test("enabled internal action credentials are pairwise distinct",{timeout:60000},async()=>{const decision="decision-functional-secret-123",monitoring="monitoring-functional-secret-123",base={DENGUEOPS_INTERNAL_DECISION_ENABLED:"true",DENGUEOPS_INTERNAL_DECISION_SECRET:decision,DENGUEOPS_INTERNAL_OPERATOR_ID:"decision-operator",DENGUEOPS_INTERNAL_MONITORING_ENABLED:"true",DENGUEOPS_INTERNAL_MONITORING_SECRET:monitoring,DENGUEOPS_INTERNAL_MONITORING_OPERATOR_ID:"monitoring-operator"};const cases=[{env:base,status:202},{env:{...base,DENGUEOPS_INTERNAL_MODEL_LIFECYCLE_SECRET:decision},status:503},{env:{...base,DENGUEOPS_INTERNAL_MODEL_LIFECYCLE_SECRET:monitoring},status:503},{env:{...base,DENGUEOPS_INTERNAL_MONITORING_SECRET:decision},status:503}];for(const value of cases){const instance=await server(true,value.env);try{const response=await fetch(`${instance.url}/api/runtime/model-lifecycle`,{method:"POST",headers:{"content-type":"application/json","x-dengueops-model-lifecycle-secret":value.env.DENGUEOPS_INTERNAL_MODEL_LIFECYCLE_SECRET??secret},body:JSON.stringify(body)});assert.equal(response.status,value.status);const text=await response.text();for(const credential of [secret,decision,monitoring])assert.equal(text.includes(credential),false)}finally{await stop(instance)}}});
test("lifecycle configuration and authentication failures redact response and process logs",{timeout:90000},async()=>{const exposed=[secret,"decision-functional-secret-123","monitoring-functional-secret-123"];const cases=[{env:{DENGUEOPS_INTERNAL_MODEL_LIFECYCLE_SECRET:""},credential:"wrong",status:503},{env:{DENGUEOPS_INTERNAL_MODEL_LIFECYCLE_OPERATOR_ID:""},credential:secret,status:503},{env:{},credential:"wrong-lifecycle-credential",status:401}];for(const value of cases){const instance=await server(true,value.env);try{const response=await fetch(`${instance.url}/api/runtime/model-lifecycle`,{method:"POST",headers:{"content-type":"application/json","x-dengueops-model-lifecycle-secret":value.credential},body:JSON.stringify(body)});assert.equal(response.status,value.status);const responseText=await response.text();await new Promise(resolve=>setTimeout(resolve,50));const logs=instance.logs();for(const candidate of [...exposed,value.credential])for(const output of [responseText,logs.stdout,logs.stderr])assert.equal(output.includes(candidate),false)}finally{await stop(instance)}}});
test("all baseline and alternate RF identities are rejected at lifecycle HTTP ingress",{timeout:30000},async()=>{const instance=await server(true);try{for(const smuggled of [{modelId:"previous_week_naive"},{modelId:"moving_average_4w"},{modelId:"seasonal_naive_52w"},{modelId:"alternate_random_forest"},{modelFamily:"AlternateRandomForest"},{parameterSha256:"0".repeat(64)}]){const response=await fetch(`${instance.url}/api/runtime/model-lifecycle`,{method:"POST",headers:{"content-type":"application/json","x-dengueops-model-lifecycle-secret":secret},body:JSON.stringify({...body,...smuggled})});assert.equal(response.status,400)}}finally{await stop(instance)}});
