import hashlib,json,math,sys,tempfile,unittest,uuid
from datetime import datetime,timezone
from pathlib import Path
import pandas as pd
ROOT=Path(__file__).resolve().parents[1];sys.path.insert(0,str(ROOT/'analytics'))
from feature_engineering import FEATURE_COLUMNS,build_features,build_inference_features
from model_factory import build_candidate_estimator,load_and_validate_candidate_registry
from runtime_commit import atomic_json,sha256_file
from runtime_worker import run_once
from tests.test_runtime_assessment_commit import build_ready_assessment_runtime,iso_now

class ApprovedForecastTests(unittest.TestCase):
 def test_all_deployable_candidates_fit_full_data_with_exact_hashes(self):
  registry,_=load_and_validate_candidate_registry();training,_=build_features(ROOT/'data/dengue_cases.csv',ROOT/'data/climate_data.csv',output_path=None);inference=build_inference_features(ROOT/'data/dengue_cases.csv',ROOT/'data/climate_data.csv');X=training[FEATURE_COLUMNS];y=training['target_cases_next_2w'];x=inference.iloc[-1][FEATURE_COLUMNS].to_frame().T
  for model_id in ('ridge_regression','poisson_regression','random_forest','gradient_boosting'):
   candidate=next(c for c in registry['candidates'] if c['model_id']==model_id);model=build_candidate_estimator(model_id,registry);model.fit(X,y);prediction=float(model.predict(x)[0]);self.assertTrue(math.isfinite(prediction));self.assertEqual(candidate['parameters_sha256'],hashlib.sha256(json.dumps(candidate['parameters'],sort_keys=True,separators=(',',':')).encode()).hexdigest())
 def test_one_reserved_authorization_commits_one_rf_run_without_comparison_or_preparedness(self):
  with tempfile.TemporaryDirectory() as directory:
   runtime,_workspace,pending,assessment_job=build_ready_assessment_runtime(Path(directory));self.assertTrue(run_once(runtime,'assessment-worker'));assessment=runtime/'assessments'/assessment_job['assessmentId'];summary=json.loads((assessment/'artifacts/assessment_summary.json').read_text());rf=next(c for c in summary['candidates'] if c['modelId']=='random_forest');decision_id,auth_id,job_id,run_id=[str(uuid.uuid4()) for _ in range(4)];created=iso_now();decision_root=runtime/'decisions'/decision_id;decision_root.mkdir(parents=True);assessment_commit_hash=sha256_file(assessment/'metadata/commit.json');decision={'decisionId':decision_id,'assessmentId':assessment_job['assessmentId'],'assessmentCommitSha256':assessment_commit_hash,'datasetId':summary['datasetId'],'deploymentId':'dhaka_south','validationRecordSha256':summary['provenance']['validationRecordSha256'],'technicalWinnerModelId':summary['technicalWinnerModelId'],'decision':'keep_current_model','selectedModelId':'random_forest','selectedModelParameterSha256':rf['parametersSha256'],'forecastAuthorized':True,'authorizationId':auth_id}
   atomic_json(decision_root/'decision.json',decision);atomic_json(decision_root/'commit.json',{'status':'committed','decisionId':decision_id});decision_commit_hash=sha256_file(decision_root/'commit.json');auth_root=runtime/'authorizations'/auth_id;auth_root.mkdir(parents=True);atomic_json(auth_root/'authorization.json',{'authorizationId':auth_id,'decisionId':decision_id,'decisionCommitSha256':decision_commit_hash});atomic_json(auth_root/'commit.json',{'authorizationSha256':sha256_file(auth_root/'authorization.json')});state=runtime/'authorization-state'/auth_id;state.mkdir(parents=True);atomic_json(state/'reservation.json',{'schemaVersion':'1.0','authorizationId':auth_id,'decisionId':decision_id,'eventType':'reserved','eventId':str(uuid.uuid4()),'createdAt':created,'jobId':job_id,'runId':run_id})
   job={'schemaVersion':'1.0','jobKind':'approved_forecast','jobId':job_id,'runId':run_id,'decisionId':decision_id,'decisionCommitSha256':decision_commit_hash,'authorizationId':auth_id,'assessmentId':assessment_job['assessmentId'],'assessmentCommitSha256':assessment_commit_hash,'workspaceId':assessment_job['assessmentId'],'datasetId':summary['datasetId'],'deploymentId':'dhaka_south','selectedModelId':'random_forest','selectedModelParameterSha256':rf['parametersSha256'],'workflowMode':'approved_assessment_forecast','validationRecordSha256':summary['provenance']['validationRecordSha256'],'status':'queued','progress':'queued','createdAt':created,'claimedAt':None,'startedAt':None,'updatedAt':created,'completedAt':None,'heartbeatAt':None,'workerId':None,'processId':None,'timeoutSeconds':600,'retryCount':0,'error':None,'committedRunId':None};atomic_json(runtime/'jobs/pending'/f'{job_id}.json',job);self.assertTrue(run_once(runtime,'approved-worker'));completed=json.loads((runtime/'jobs/completed'/f'{job_id}.json').read_text());self.assertEqual(completed['committedRunId'],run_id);run=runtime/'runs'/run_id;output=json.loads((run/'artifacts/forecast_output.json').read_text());uncertainty=json.loads((run/'artifacts/forecast_uncertainty.json').read_text());self.assertEqual(output['workflowMode'],'approved_assessment_forecast');self.assertFalse(output['deploymentModelAdopted']);self.assertEqual(uncertainty['uncertaintyStatus'],'pending_selected_model_calibration');self.assertIsNone(uncertainty['lowerRaw']);self.assertFalse((run/'artifacts/candidate_model_comparison.json').exists());self.assertFalse((run/'artifacts/directives.json').exists());self.assertTrue((state/'consumption.json').exists())
if __name__=='__main__':unittest.main()
