import {createHash,randomUUID,timingSafeEqual} from "node:crypto";
import {loadRuntimeConfig} from "@/lib/runtime/config";
import {RuntimePublicError,errorResponse} from "@/lib/runtime/errors";
import {deterministicLifecycleDecisionId,findLifecycleIdempotency,readModelLifecycleSummary} from "@/lib/runtime/model-lifecycle-store";
import {MODEL_LIFECYCLE_POLICY_SHA,LIFECYCLE_PROFILE_SHA} from "@/lib/runtime/model-lifecycle-policy";
import {createPendingJob,initializeRuntimeRoot} from "@/lib/runtime/store";
import {jobRecordPath,runtimeCollectionPaths} from "@/lib/runtime/paths";
import type {LifecycleAction,ModelLifecycleJobRecord} from "@/lib/runtime/contracts";

export const runtime="nodejs";
const SHA=/^[a-f0-9]{64}$/;
const actions=new Set<LifecycleAction>(["bootstrap_historical_profile","retain_current_model","promote_selected_model","rollback_previous_assignment","defer","reject"]);
const acknowledgements=["manualActionAcknowledged","statisticalSufficiencyNotGovernedAcknowledged","materialWorseningNotClassifiedAcknowledged","evidenceDoesNotProveSuperiorityAcknowledged","quickCompatibleRandomForestOnlyAcknowledged"] as const;
const promotionHashes=["expectedAssessmentCommitSha256","expectedDecisionCommitSha256","expectedAuthorizationCommitSha256","expectedApprovedForecastCommitSha256","expectedOutcomeCommitSha256","expectedMonitoringLatestSha256","expectedMonitoringSummarySha256","expectedMonitoringIncludedOutcomeSetSha256","expectedDegradationLatestSha256","expectedDegradationEvidenceCommitSha256","expectedDegradationEvidenceSha256"] as const;
const contextHashes=["expectedMonitoringLatestSha256","expectedMonitoringSummarySha256","expectedMonitoringIncludedOutcomeSetSha256","expectedDegradationLatestSha256","expectedDegradationEvidenceCommitSha256","expectedDegradationEvidenceSha256"] as const;
const common=new Set(["deployment","action","expectedAssignmentPointerState","expectedAssignmentPointerSha256","reason",...acknowledgements]);
function secretEqual(left:string,right:string){const a=createHash("sha256").update(left).digest(),b=createHash("sha256").update(right).digest();return timingSafeEqual(a,b)&&left.length===right.length}
function exactKeys(body:Record<string,unknown>,extra:readonly string[]){const allowed=new Set([...common,...extra]);if(Object.keys(body).some(key=>!allowed.has(key)))throw new RuntimePublicError("unexpected_model_lifecycle_field","validation","The lifecycle request contains an unsupported or client-selected identity.",400)}
function requireHashes(body:Record<string,unknown>,names:readonly string[]){for(const name of names)if(!SHA.test(String(body[name]??"")))throw new RuntimePublicError("invalid_lifecycle_evidence_hash","validation","A lifecycle evidence hash is invalid.",400)}

export async function GET(){const correlationId=randomUUID();try{const config=loadRuntimeConfig(false),summary=await readModelLifecycleSummary(config.repositoryRoot,config.runtimeRoot,config.defaultDeploymentId);return Response.json({ok:true,...summary},{headers:{"Cache-Control":"no-store"}})}catch(error){const failure=errorResponse(error,correlationId);return Response.json(failure.body,{status:failure.status,headers:{"Cache-Control":"no-store"}})}}

export async function POST(request:Request){const correlationId=randomUUID();try{
  const config=loadRuntimeConfig(false);if(!config.internalModelLifecycleEnabled)throw new RuntimePublicError("model_lifecycle_disabled","configuration","Model lifecycle ingress is disabled.",503);
  const supplied=request.headers.get("x-dengueops-model-lifecycle-secret")??"";if(!secretEqual(supplied,config.internalModelLifecycleSecret))throw new RuntimePublicError("model_lifecycle_unauthorized","validation","Model lifecycle authorization failed.",401);
  const body=await request.json() as Record<string,unknown>,action=body.action as LifecycleAction;
  if(body.deployment!=="dhaka_south"||!actions.has(action)||typeof body.reason!=="string"||!body.reason.trim()||body.reason.length>1000||acknowledgements.some(key=>body[key]!==true))throw new RuntimePublicError("invalid_model_lifecycle_request","validation","The lifecycle action, reason, or acknowledgement set is invalid.",400);
  if(!["absent","present"].includes(String(body.expectedAssignmentPointerState))||(body.expectedAssignmentPointerState==="present"?!SHA.test(String(body.expectedAssignmentPointerSha256??"")):body.expectedAssignmentPointerSha256!==null))throw new RuntimePublicError("invalid_assignment_pointer_expectation","validation","The expected assignment pointer state is invalid.",400);
  let actionFields:Record<string,unknown>={};
  if(action==="bootstrap_historical_profile"){exactKeys(body,["expectedProfileSha256"]);if(body.expectedAssignmentPointerState!=="absent"||body.expectedProfileSha256!==LIFECYCLE_PROFILE_SHA)throw new RuntimePublicError("bootstrap_profile_mismatch","validation","The historical profile or pointer expectation does not match governance.",409);actionFields={expectedProfileSha256:body.expectedProfileSha256};}
  else if(action==="promote_selected_model"){exactKeys(body,promotionHashes);requireHashes(body,promotionHashes);actionFields=Object.fromEntries(promotionHashes.map(key=>[key,body[key]]));}
  else if(action==="retain_current_model"){exactKeys(body,["evidenceContextStatus",...contextHashes]);if(body.evidenceContextStatus!=="verified_monitoring_and_degradation")throw new RuntimePublicError("invalid_lifecycle_evidence_context","validation","Verified monitoring and degradation evidence is required.",400);requireHashes(body,contextHashes);actionFields={evidenceContextStatus:body.evidenceContextStatus,...Object.fromEntries(contextHashes.map(key=>[key,body[key]]))};}
  else if(action==="reject"){if(body.evidenceContextStatus==="verified_assessment_and_decision"){const hashes=["expectedAssessmentCommitSha256","expectedDecisionCommitSha256"] as const;exactKeys(body,["evidenceContextStatus",...hashes]);requireHashes(body,hashes);actionFields={evidenceContextStatus:body.evidenceContextStatus,...Object.fromEntries(hashes.map(key=>[key,body[key]]))};}else{exactKeys(body,["evidenceContextStatus",...contextHashes]);if(body.evidenceContextStatus!=="verified_monitoring_and_degradation")throw new RuntimePublicError("invalid_lifecycle_evidence_context","validation","The reject evidence context is invalid.",400);requireHashes(body,contextHashes);actionFields={evidenceContextStatus:body.evidenceContextStatus,...Object.fromEntries(contextHashes.map(key=>[key,body[key]]))};}}
  else if(action==="defer"){if(body.evidenceContextStatus==="explicit_no_evidence"){exactKeys(body,["evidenceContextStatus"]);actionFields={evidenceContextStatus:body.evidenceContextStatus};}else{exactKeys(body,["evidenceContextStatus",...contextHashes]);if(body.evidenceContextStatus!=="verified_monitoring_and_degradation")throw new RuntimePublicError("invalid_lifecycle_evidence_context","validation","The defer evidence context is invalid.",400);requireHashes(body,contextHashes);actionFields={evidenceContextStatus:body.evidenceContextStatus,...Object.fromEntries(contextHashes.map(key=>[key,body[key]]))};}}
  else {exactKeys(body,[]);if(body.expectedAssignmentPointerState!=="present")throw new RuntimePublicError("rollback_requires_assignment_pointer","validation","Rollback requires a current assignment pointer.",409);}
  const acknowledgementFields={manualActionAcknowledged:true,statisticalSufficiencyNotGovernedAcknowledged:true,materialWorseningNotClassifiedAcknowledged:true,evidenceDoesNotProveSuperiorityAcknowledged:true,quickCompatibleRandomForestOnlyAcknowledged:true} as const;
  await initializeRuntimeRoot(config.runtimeRoot);const idempotencyInput={action,expectedAssignmentPointerState:body.expectedAssignmentPointerState as "absent"|"present",expectedAssignmentPointerSha256:body.expectedAssignmentPointerSha256 as string|null,operatorIdentifier:config.internalModelLifecycleOperatorId,reason:body.reason.trim(),...acknowledgementFields,...actionFields} as Parameters<typeof findLifecycleIdempotency>[2];const prior=await findLifecycleIdempotency(config.repositoryRoot,config.runtimeRoot,idempotencyInput);
  if(prior){if(prior.conflict)throw new RuntimePublicError("model_lifecycle_request_conflict","validation","A lifecycle decision exists for this snapshot with conflicting reason or acknowledgements.",409);return Response.json({ok:true,lifecycleDecisionId:prior.existingId,status:"completed",idempotent:true},{status:200})}
  const now=new Date().toISOString(),jobId=randomUUID(),lifecycleDecisionId=deterministicLifecycleDecisionId(idempotencyInput);const job={schemaVersion:"1.0",jobKind:"model_lifecycle",jobId,lifecycleDecisionId,deploymentId:"dhaka_south",geography:{level:"city",id:"BGD-DHAKA-SOUTH",name:"Dhaka South"},workflowMode:"model_lifecycle",policyId:"RUNTIME.MODEL_LIFECYCLE.DECISION",policyVersion:"p2-v1",policySha256:MODEL_LIFECYCLE_POLICY_SHA,action,operatorIdentifier:config.internalModelLifecycleOperatorId,reason:body.reason.trim(),...acknowledgementFields,expectedAssignmentPointerState:body.expectedAssignmentPointerState,expectedAssignmentPointerSha256:body.expectedAssignmentPointerSha256,...actionFields,status:"queued",progress:"queued",createdAt:now,claimedAt:null,startedAt:null,updatedAt:now,completedAt:null,heartbeatAt:null,workerId:null,processId:null,timeoutSeconds:600,retryCount:0,error:null,committedLifecycleDecisionId:null} as ModelLifecycleJobRecord;
  await createPendingJob(jobRecordPath(runtimeCollectionPaths(config.runtimeRoot).pendingJobs,jobId),job);return Response.json({ok:true,jobId,lifecycleDecisionId,status:"queued",statusUrl:`/api/runtime/jobs/${jobId}`},{status:202});
}catch(error){const failure=errorResponse(error,correlationId);return Response.json(failure.body,{status:failure.status})}}
