"use client";

import { useEffect,useState } from "react";
import { getMonitoringSummary } from "@/lib/runtime/client";
import type { MonitoringSummaryResponse } from "@/lib/runtime/contracts";
import StatusBadge from "@/components/ui/StatusBadge";

const KNOWN=new Set(["quick_forecast_p1","approved_forecast_p1","approved_forecast_p2"]);
const metric=(value:number|null|undefined,digits=2)=>value==null?"Not available":value.toFixed(digits);
const label=(identity:string)=>identity.split("|")[0].replaceAll("_"," ");

export default function ForecastOutcomeMonitoringSummary(){
  const[state,setState]=useState<MonitoringSummaryResponse|null>(null);
  useEffect(()=>{let active=true;getMonitoringSummary().then(value=>{if(active)setState(value)});return()=>{active=false}},[]);
  if(state==null)return <section className="mb-10 rounded-xl border border-border bg-surface p-5" aria-label="Forecast outcome monitoring"><p className="text-sm text-secondary">Loading governed outcome evidence…</p></section>;
  if(!state.ok){const missing=state.error.code==="monitoring_summary_not_found";return <section className="mb-10 rounded-xl border border-border bg-surface p-5" aria-label="Forecast outcome monitoring"><StatusBadge label={missing?"Actuals pending":"Evidence unavailable"} variant={missing?"warning":"destructive"}/><h2 className="mt-3 text-xl font-bold text-primary">Forecast outcome monitoring</h2><p className="mt-2 text-sm text-secondary">{missing?"No governed actual observation has been committed yet. Missing actuals are pending evidence, not integrity failures.":state.error.message}</p></section>}
  const summary=state.summary;const sources=summary.sourceFamilyBreakdowns??[{identity:"quick_forecast_p1",evaluatedForecastCount:summary.evaluatedForecastCount,cumulativeMAE:summary.cumulativeMAE,cumulativeRMSE:summary.cumulativeRMSE,cumulativeBias:summary.cumulativeBias}];
  if(sources.some(item=>!KNOWN.has(item.identity)))return <section className="mb-10 rounded-xl border border-destructive/30 bg-destructive/10 p-5"><StatusBadge label="Unknown source rejected" variant="destructive"/><p className="mt-3 text-sm text-secondary">Monitoring evidence contains an unknown source family and is not displayed.</p></section>;
  const cards=[["Monitored",String(summary.evaluatedForecastCount)],["Pending actuals",String(summary.pendingOutcomeCount)],["MAE",metric(summary.cumulativeMAE)],["RMSE",metric(summary.cumulativeRMSE)],["Bias",metric(summary.cumulativeBias)],["MAPE",summary.cumulativeMAPE==null?"Not eligible":`${metric(summary.cumulativeMAPE)}%`]];
  return <section className="mb-10 rounded-2xl border border-border bg-surface p-6" aria-labelledby="forecast-monitoring-heading"><div className="flex flex-wrap gap-2"><StatusBadge label="Evidence only" variant="info"/><StatusBadge label={summary.policyVersion} variant="neutral"/></div><h2 id="forecast-monitoring-heading" className="mt-3 text-2xl font-bold text-primary">Forecast outcome monitoring</h2><p className="mt-2 text-sm text-secondary">Exact-period actuals are compared with immutable runtime forecasts. Monitoring does not classify degradation, promote, retain, replace, or roll back a model.</p><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-6">{cards.map(([name,value])=><div key={name} className="rounded-xl border border-border bg-background p-4"><p className="text-[10px] uppercase tracking-wider text-text-muted">{name}</p><p className="mt-2 text-lg font-bold text-primary">{value}</p></div>)}</div><div className="mt-5 grid gap-5 lg:grid-cols-2"><div><h3 className="font-semibold text-primary">Source families</h3><ul className="mt-2 space-y-2 text-sm text-secondary">{sources.map(item=><li key={item.identity} className="flex justify-between gap-4"><span className="capitalize">{label(item.identity)}</span><span>{item.evaluatedForecastCount} monitored</span></li>)}</ul></div><div><h3 className="font-semibold text-primary">Selected models</h3><ul className="mt-2 space-y-2 text-sm text-secondary">{summary.modelBreakdowns.map(item=><li key={item.identity} className="flex justify-between gap-4"><span className="capitalize">{label(item.identity)}</span><span>MAE {metric(item.cumulativeMAE)}</span></li>)}</ul></div></div><div className="mt-5 rounded-xl border border-border bg-background p-4 text-sm text-secondary"><p>Latest target: <strong className="text-primary">{summary.latestEvaluatedTargetPeriod}</strong></p><p className="mt-1">Percentage metrics: {summary.percentageMetricEvaluatedCount} eligible; {summary.zeroObservedCount} zero-actual observation(s) excluded from percentage error only.</p><p className="mt-1">Empirical range: {summary.empiricalCoverage==null?"not available":`${metric(summary.empiricalCoverage*100)}% coverage across ${summary.empiricalRangeEvaluatedCount} eligible outcome(s)`}.</p>{summary.latestSourceEvidence?<p className="mt-1">Latest source evidence: {summary.latestSourceEvidence.trainingRowCount??"Quick Forecast governed history"} training rows; {summary.latestSourceEvidence.plannedFoldCount??"Quick Forecast governed calibration"} assessment folds.</p>:null}</div><p className="mt-4 text-xs text-secondary">Protected observation submission remains trusted server-side ingress. This read-only panel contains no monitoring credential and triggers no lifecycle action.</p></section>;
}
