"use client";
import { useState } from "react";
import Button from "@/components/ui/Button";
import type { AssessmentDecisionWorkflowProjection, DatasetAssessmentResultSuccess, DecisionChoice, DecisionResultSuccess } from "@/lib/runtime/contracts";
import { modelLabel, statusLabel } from "@/lib/status-labels";

export default function ApprovalPanel({assessment,decision,workflowDecision=null,busy,onDecision,onForecast}:{assessment:DatasetAssessmentResultSuccess;decision:DecisionResultSuccess|null;workflowDecision?:AssessmentDecisionWorkflowProjection|null;busy:boolean;onDecision:(choice:DecisionChoice,reason:string)=>void;onForecast:()=>void}){
  const [reason,setReason]=useState("");const [confirmed,setConfirmed]=useState(false);const winner=assessment.workflow.candidates.find(value=>value.modelId===assessment.technicalWinnerModelId);const winnerAllowed=Boolean(winner?.deployableForOneRun&&winner.completionStatus==="complete");
  const recorded=decision??workflowDecision;
  if(recorded){const selectedLabel=decision?.selectedModelLabel??(recorded.selectedModelId?modelLabel(recorded.selectedModelId):null);const committed="forecastStatus" in recorded&&recorded.forecastStatus==="committed";return <section className="rounded-xl border border-border-subtle bg-surface p-5"><h2 className="font-semibold text-ink">{statusLabel(recorded.decisionStatus)}</h2><p className="mt-2 text-sm text-ink-muted">Decision {recorded.decisionId} · {selectedLabel??"No forecast model selected"}</p><p className="mt-2 text-xs text-warning">Trusted internal, unverified operator · one forecast run only · deployment-wide model unchanged.</p>{committed?<p className="mt-4 text-sm text-success">The authorized one-run forecast committed successfully. Run {workflowDecision?.committedRunId}.</p>:recorded.forecastAuthorized?<Button className="mt-4" disabled={busy||recorded.authorizationStatus!=="available"} onClick={onForecast}>Generate Approved Forecast</Button>:<p className="mt-4 text-sm text-ink-muted">This outcome does not authorize a forecast.</p>}</section>}
  return <section className="rounded-xl border border-border-subtle bg-surface p-5"><h2 className="font-semibold text-ink">Trusted internal one-run model decision</h2><ul className="mt-3 space-y-1 text-sm text-warning"><li>Technical evidence only; recommendation strength is not available.</li><li>Operator identity and institutional approval are not verified.</li><li>The decision applies to one forecast run and does not change the deployment model.</li></ul><label className="mt-4 block text-sm font-medium text-ink" htmlFor="decision-reason">Decision reason</label><textarea id="decision-reason" value={reason} maxLength={1000} onChange={e=>setReason(e.target.value)} className="mt-2 min-h-24 w-full rounded-lg border border-border bg-surface-muted p-3 text-sm text-ink focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-focus"/><label className="mt-3 flex items-start gap-2 text-sm text-ink-muted"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)} className="mt-1"/>I understand this immutable decision is irreversible except for governed defer supersession and is not deployment-wide adoption.</label><div className="mt-4 flex flex-wrap gap-2"><Button disabled={busy||!confirmed||!reason.trim()||!winnerAllowed} onClick={()=>onDecision("approve_technical_winner",reason.trim())}>Use {assessment.technicalWinnerModelId?modelLabel(assessment.technicalWinnerModelId):"technical winner"} for one forecast</Button><Button variant="secondary" disabled={busy||!confirmed||!reason.trim()} onClick={()=>onDecision("keep_current_model",reason.trim())}>Keep current Random Forest for one forecast</Button><Button variant="secondary" disabled={busy||!confirmed||!reason.trim()} onClick={()=>onDecision("defer",reason.trim())}>Defer</Button><Button variant="quiet" disabled={busy||!confirmed||!reason.trim()} onClick={()=>onDecision("reject_assessment",reason.trim())}>Reject assessment</Button></div>{!winnerAllowed?<p className="mt-3 text-xs text-warning">The technical winner is an evaluation-only baseline or otherwise not runtime-deployable. It cannot be selected for forecasting, and no learned runner-up will be substituted automatically.</p>:null}</section>;
}
