/**
 * demo-data.ts
 *
 * Exports analytics outputs as typed objects for client components.
 *
 * Primary sources:  Generated JSON files under data/ (analytics pipeline output)
 * Placeholder analytical evidence is never exported as active model evidence.
 */

// ── Generated by analytics pipeline ─────────────────────────────────────────
import forecastOutputRaw from "@/data/forecast_output.json";
import zonesRaw from "@/data/zones.json";
import facilitiesRaw from "@/data/facilities.json";
import inventoryRaw from "@/data/inventory.json";
// directives.json is a wrapper object: { directives: [...], summary: {...}, ... }
import directivesFileRaw from "@/data/directives.json";
// Dashboard-ready outputs from analytics/dashboard_exporter.py
import dashboardSummaryRaw from "@/data/dashboard_summary.json";
import modelComparisonRaw from "@/data/model_comparison.json";
import chartDataRaw from "@/data/chart_data.json";
// Pipeline run log
import pipelineRunSummaryRaw from "@/data/pipeline_run_summary.json";

// ── Placeholder (pipeline does not yet produce these shapes) ─────────────────
import validationMetricsRaw from "@/data/validation_metrics.json";

import type {
  ForecastOutput,
  ValidationMetrics,
  Zone,
  Facility,
  Inventory,
  Directive,
  DashboardSummary,
  PipelineRunSummary,
} from "./types";
import type { EvidenceViewModel, OverviewViewModel, PreparednessViewModel } from "./forecast-workflow-types";

const directivesFile = directivesFileRaw as unknown as { directives: Directive[]; summary: Record<string, number | string> };
const dashboardSummaryTyped = dashboardSummaryRaw as unknown as DashboardSummary;

export const forecastOutput = forecastOutputRaw as unknown as ForecastOutput;
export const validationMetrics = validationMetricsRaw as unknown as ValidationMetrics;
export const featureDiagnostics = dashboardSummaryTyped.feature_importance;
export const zones = zonesRaw as unknown as Zone[];
export const facilities = facilitiesRaw as unknown as Facility[];
export const inventory = inventoryRaw as unknown as Inventory[];
export const directives = (directivesFile.directives ?? []) as Directive[];
export const directivesSummary = directivesFile.summary as {
  total_zones: number;
  total_facilities: number;
  total_public_government_anchors: number;
  facilities_with_expected_bed_gap: number;
  facilities_with_worst_case_bed_gap: number;
  critical_supply_alerts: number;
  highest_priority_zone: string;
  highest_pressure_facility: string;
};

// ── Dashboard-ready outputs ──────────────────────────────────────────────────
export const dashboardSummary = dashboardSummaryTyped;
export const rollingValidation = dashboardSummary.rolling_validation;
export const candidateModelComparison = dashboardSummary.candidate_model_comparison;
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const modelComparison = modelComparisonRaw as any;
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const chartData = chartDataRaw as any;
export const pipelineRunSummary = pipelineRunSummaryRaw as unknown as PipelineRunSummary;

const activeAlerts = directives.flatMap((directive) => directive.inventory_alerts.map((alert) => ({
  facilityName: directive.facility_name,
  level: alert.alert_level,
  message: alert.message,
})));
const currentApprovedModelId = dashboardSummary.candidate_model_comparison.current_forecast_model;
const currentApprovedModelLabel = currentApprovedModelId.split("_").map((part) => part[0]?.toUpperCase() + part.slice(1)).join(" ");
const deploymentGate = dashboardSummary.workflow_metadata?.deployment_gate
  ?? dashboardSummary.deployment_profile?.deployment_gate
  ?? "benchmark_only";

export const overviewViewModel: OverviewViewModel = {
  latestObservedCases: forecastOutput.latest_observed_cases,
  pointForecast: dashboardSummary.uncertainty.point_forecast_reported,
  empiricalLower: dashboardSummary.uncertainty.interval_lower_reported,
  empiricalUpper: dashboardSummary.uncertainty.interval_upper_reported,
  targetPeriod: `${forecastOutput.target_epi_year}-W${String(forecastOutput.target_epi_week).padStart(2, "0")}`,
  forecastDirection: forecastOutput.forecast_growth_category,
  activeModelLabel: dashboardSummary.workflow_metadata?.current_approved_model_label ?? currentApprovedModelLabel,
  deploymentMode: dashboardSummary.deployment_profile?.demonstration_status ?? "synthetic_capability_demonstration",
  deploymentGate,
  latestRun: { runId: pipelineRunSummary.provenance.run_id, run_timestamp: pipelineRunSummary.run_timestamp, status: pipelineRunSummary.status, completedSteps: pipelineRunSummary.completed_steps.length },
  facilities: directives,
  activeAlerts,
};

export const preparednessViewModel: PreparednessViewModel = {
  scenarios: forecastOutput.preparedness_scenarios,
  facilities: directives,
  empiricalRange: dashboardSummary.uncertainty,
  scenarioRelationship: "The empirical forecast range describes forecast uncertainty evidence. Planning scenarios are separate operational inputs used by the current preparedness logic.",
};

export const evidenceViewModel: EvidenceViewModel = {
  comparison: dashboardSummary.candidate_model_comparison,
  uncertainty: dashboardSummary.uncertainty,
  explainability: dashboardSummary.feature_importance,
  provenance: dashboardSummary.provenance,
  deploymentMode: dashboardSummary.deployment_profile?.demonstration_status ?? "synthetic_capability_demonstration",
  deploymentGate,
  limitations: dashboardSummary.candidate_model_comparison.limitations ?? [],
};
