import dashboardSummaryRaw from "@/data/dashboard_summary.json";

// Canonical policy is generated by the Python formula registry.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const policy = (dashboardSummaryRaw as any).formula_policy ?? {};
const stockThresholds = policy["OPS.STOCK.THRESHOLDS"]?.parameters ?? {};
const SDH_CRITICAL_DAYS = Number(stockThresholds.critical_days ?? 3);
const SDH_NS1_WARNING_DAYS = Number(stockThresholds.ns1_warning_days ?? 7);

export function formatPriorityScore(score: number): string {
  return score.toFixed(2);
}

export function getSdhSeverity(days: number): "ok" | "warning" | "critical" {
  if (days <= SDH_CRITICAL_DAYS) return "critical";
  if (days <= SDH_NS1_WARNING_DAYS) return "warning";
  return "ok";
}

export function getSdhLabel(days: number): string {
  if (days <= SDH_CRITICAL_DAYS) return `${days}d – PROTOTYPE CRITICAL TRIGGER`;
  if (days <= SDH_NS1_WARNING_DAYS) return `${days}d – PROTOTYPE WARNING TRIGGER`;
  return `${days}d – Above prototype threshold`;
}
