import type { RiskLevel } from "./types";
import { RISK_COLORS } from "./constants";
import dashboardSummaryRaw from "@/data/dashboard_summary.json";

// Canonical policy is generated by the Python formula registry.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const policy = (dashboardSummaryRaw as any).formula_policy ?? {};
const stockThresholds = policy["OPS.STOCK.THRESHOLDS"]?.parameters ?? {};
const SDH_CRITICAL_DAYS = Number(stockThresholds.critical_days ?? 3);
const SDH_NS1_WARNING_DAYS = Number(stockThresholds.ns1_warning_days ?? 7);

/**
 * Returns the full Tailwind class object for a given risk level.
 */
export function getRiskColor(level: RiskLevel) {
  return RISK_COLORS[level] ?? RISK_COLORS["Low"];
}

/**
 * Returns a variant string used by RiskBadge to pick its visual style.
 */
export function getRiskBadgeVariant(level: RiskLevel): "low" | "moderate" | "high" | "critical" {
  return level.toLowerCase() as "low" | "moderate" | "high" | "critical";
}

/**
 * Classifies a numeric risk score (0–100) into a RiskLevel.
 */
export function classifyRiskLevel(score: number): RiskLevel {
  const headline = (dashboardSummaryRaw as any).headline_metrics ?? {};
  return score === Number(headline.experimental_growth_score ?? headline.risk_score)
    ? (headline.risk_level as RiskLevel)
    : "Low";
}

/**
 * Formats a priority score to 2 decimal places.
 */
export function formatPriorityScore(score: number): string {
  return score.toFixed(2);
}

/**
 * Returns a hex color string suitable for Recharts given a risk level.
 */
export function getRiskHex(level: RiskLevel): string {
  return RISK_COLORS[level]?.hex ?? "#64748b";
}

/**
 * Determines alert severity based on SDH days remaining.
 */
export function getSdhSeverity(days: number): "ok" | "warning" | "critical" {
  if (days <= SDH_CRITICAL_DAYS) return "critical";
  if (days <= SDH_NS1_WARNING_DAYS) return "warning";
  return "ok";
}

/**
 * Returns a human-readable SDH status label.
 */
export function getSdhLabel(days: number): string {
  if (days <= SDH_CRITICAL_DAYS) return `${days}d – PROTOTYPE CRITICAL TRIGGER`;
  if (days <= SDH_NS1_WARNING_DAYS) return `${days}d – PROTOTYPE WARNING TRIGGER`;
  return `${days}d – Above prototype threshold`;
}
