const STATUS_LABELS: Record<string, string> = {
  comparison_complete_and_adopted: "Comparison complete — selected model adopted",
  "adopted_p1.2b": "Adopted through governed model review",
  temporally_evaluated_synthetic_empirical_range: "Temporally evaluated synthetic empirical range",
  benchmark_only: "Benchmark only",
  synthetic_capability_demonstration: "Synthetic capability demonstration",
  random_forest: "Random Forest",
  gradient_boosting: "Gradient Boosting",
  not_evaluated_across_temporal_folds: "Temporal importance stability not evaluated",
  operational_planning_compatibility_only_not_forecast_interval: "Planning compatibility only — not a forecast interval",
  passed: "Passed",
  success: "Committed successfully",
  active: "Active",
  complete: "Complete",
  dataset_assessment: "Dataset assessment",
  assessment_queued: "Assessment queued",
  preparing_assessment: "Preparing assessment",
  building_features: "Building governed features",
  creating_fold_plan: "Creating common temporal fold plan",
  checking_candidate_eligibility: "Checking candidate eligibility",
  evaluating_previous_week_naive: "Evaluating previous-week naive",
  evaluating_moving_average_4w: "Evaluating four-week moving average",
  evaluating_seasonal_naive_52w: "Evaluating seasonal naive",
  evaluating_ridge_regression: "Evaluating Ridge",
  evaluating_poisson_regression: "Evaluating Poisson",
  evaluating_random_forest: "Evaluating Random Forest",
  evaluating_gradient_boosting: "Evaluating Gradient Boosting",
  aggregating_metrics: "Aggregating governed metrics",
  selecting_technical_winner: "Selecting technical winner",
  preparing_recommendation: "Preparing evidence-only recommendation",
  validating_evidence: "Validating assessment evidence",
  committing_assessment: "Committing immutable assessment",
  assessment_complete: "Assessment complete",
  decision_pending: "Model-use decision pending",
  decision_recorded: "Model-use decision recorded",
  approved_technical_winner: "Technical winner selected for one run",
  current_model_retained: "Current Random Forest retained for one run",
  deferred: "Decision deferred",
  assessment_rejected: "Assessment rejected",
  forecast_authorized: "One forecast run authorized",
  forecast_authorization_reserved: "Forecast authorization reserved",
  forecast_authorization_consumed: "Forecast authorization consumed",
  forecast_execution_failed: "Approved forecast failed",
  decision_superseded: "Decision superseded",
  one_run_scope: "One-run scope",
  trusted_internal_unverified: "Trusted internal operator — identity not verified",
  approved_assessment_forecast: "Approved assessment forecast",
  preparing_approved_forecast: "Preparing approved forecast",
  verifying_decision: "Verifying decision",
  verifying_assessment: "Verifying assessment",
  loading_immutable_inputs: "Loading immutable assessment inputs",
  training_selected_model: "Training selected model",
  generating_point_forecast: "Generating point forecast",
  preparing_forecast_evidence: "Preparing forecast evidence",
  updating_latest_pointer: "Updating latest committed dashboard",
  pending_selected_model_calibration: "Selected-model calibration pending",
  evidence_only: "Technical evidence only",
  recommendation_strength_not_available: "Recommendation strength not available",
  approval_pending: "Awaiting model decision",
  not_adopted: "Not adopted",
  candidate_ineligible: "Candidate ineligible",
  candidate_incomplete: "Candidate incomplete",
  partial_candidate_set: "Partial candidate set",
  insufficient_candidate_breadth: "Insufficient candidate breadth",
  complete_candidate_set: "Complete candidate set",
};

export function statusLabel(value: string | null | undefined): string {
  if (!value) return "Unavailable";
  return STATUS_LABELS[value] ?? value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
}

export function modelLabel(value: string | null | undefined): string {
  return statusLabel(value);
}
