import { createHash } from "node:crypto";
import { readFile } from "node:fs/promises";
import path from "node:path";
import { RuntimePublicError } from "./errors";
export interface ForecastOutcomePolicy { policy_id:"RUNTIME.FORECAST_OUTCOME.MONITORING";policy_version:"p1.4g-v1";policy_status:"active";policy_sha256:string;deployment_id:"dhaka_south";geography:{level:"city";id:"BGD-DHAKA-SOUTH";name:"Dhaka South"};timezone:"Asia/Dhaka";forecast_scope:Record<string,unknown>;observation_scope:{source_type:"synthetic_benchmark";source_id:"dhaka_south_synthetic_benchmark";operator_type:"trusted_internal_unverified"};formula_registry:{version:string;sha256:string;referenced_formula_ids:string[]}; }
function canonical(value:unknown):string { if(Array.isArray(value))return `[${value.map(canonical).join(",")}]`;if(value&&typeof value==="object")return `{${Object.entries(value as Record<string,unknown>).sort(([a],[b])=>a<b?-1:a>b?1:0).map(([k,v])=>`${JSON.stringify(k)}:${canonical(v)}`).join(",")}}`;return JSON.stringify(value); }
export async function loadForecastOutcomePolicy(repositoryRoot:string):Promise<ForecastOutcomePolicy>{
  const policy=JSON.parse(await readFile(path.join(repositoryRoot,"config","deployments","dhaka_south","forecast_outcome_policy.json"),"utf8")) as ForecastOutcomePolicy;const content={...policy} as Record<string,unknown>;delete content.policy_sha256;const digest=createHash("sha256").update(canonical(content)).digest("hex");
  const quick=JSON.parse(await readFile(path.join(repositoryRoot,"config","deployments","dhaka_south","quick_forecast_policy.json"),"utf8")) as Record<string,unknown>;const quickContent={...quick};delete quickContent.policy_sha256;const quickDigest=createHash("sha256").update(canonical(quickContent)).digest("hex");const profile=JSON.parse(await readFile(path.join(repositoryRoot,"config","deployments","dhaka_south","profile.json"),"utf8")) as Record<string,any>;const registry=createHash("sha256").update(await readFile(path.join(repositoryRoot,"config","candidate_models.json"))).digest("hex");const formulaBytes=await readFile(path.join(repositoryRoot,"config","formulas.json"));const formulas=createHash("sha256").update(formulaBytes).digest("hex");const formulaRegistry=JSON.parse(formulaBytes.toString("utf8")) as Record<string,any>;const scope=policy.forecast_scope;const formulaIds=new Set((formulaRegistry.formulas as Array<Record<string,unknown>>).map(item=>item.formula_id));
  if(policy.policy_id!=="RUNTIME.FORECAST_OUTCOME.MONITORING"||policy.policy_version!=="p1.4g-v1"||policy.policy_status!=="active"||policy.policy_sha256!==digest||policy.deployment_id!=="dhaka_south"||quick.policy_id!==scope.required_policy_id||quick.policy_version!==scope.required_policy_version||quick.policy_sha256!==quickDigest||scope.required_policy_sha256!==quickDigest||scope.model_parameters_sha256!==profile.model?.model_parameters_sha256||scope.feature_order_sha256!==profile.forecast_uncertainty?.feature_order_sha256||scope.candidate_registry_sha256!==registry||policy.formula_registry.sha256!==formulas||policy.formula_registry.version!==formulaRegistry.registry_version||policy.formula_registry.referenced_formula_ids.join("|")!=="METRIC.MAE|METRIC.RMSE|METRIC.MAPE"||policy.formula_registry.referenced_formula_ids.some(id=>!formulaIds.has(id)))throw new RuntimePublicError("forecast_outcome_policy_invalid","configuration","The governed forecast-outcome policy is unavailable or invalid.",503);
  return policy;
}
