import { createHash, randomUUID, timingSafeEqual } from "node:crypto";
import { loadRuntimeConfig } from "@/lib/runtime/config";
import type { DecisionResponse, RecordDecisionRequest } from "@/lib/runtime/contracts";
import { recordDecision, type DecisionChoice } from "@/lib/runtime/decision-store";
import { errorResponse, RuntimePublicError } from "@/lib/runtime/errors";
import { initializeRuntimeRoot } from "@/lib/runtime/store";
import { modelLabel } from "@/lib/status-labels";

export const runtime = "nodejs";
const SHA=/^[a-f0-9]{64}$/; const CHOICES=new Set<DecisionChoice>(["approve_technical_winner","keep_current_model","defer","reject_assessment"]);
function authorized(request:Request, configured:string){const provided=request.headers.get("x-dengueops-internal-decision-secret")??"";const a=createHash("sha256").update(configured).digest(),b=createHash("sha256").update(provided).digest();return timingSafeEqual(a,b)&&configured.length>=16;}

export async function POST(request:Request,context:{params:Promise<{assessmentId:string}>}):Promise<Response>{const correlationId=randomUUID();try{const config=loadRuntimeConfig(false);if(!config.internalDecisionEnabled||!config.internalDecisionSecret||!config.internalOperatorId)throw new RuntimePublicError("internal_decision_disabled","configuration","Trusted internal model decisions are disabled.",503);if(!authorized(request,config.internalDecisionSecret))throw new RuntimePublicError("internal_decision_forbidden","validation","The trusted internal decision credential is invalid.",403);const {assessmentId}=await context.params;const body=await request.json() as Record<string,unknown>;if(Object.keys(body).sort().join("|")!==["decision","expectedAssessmentSummarySha256","reason"].sort().join("|"))throw new RuntimePublicError("invalid_decision_request","validation","The decision request contains unsupported fields.",400);const decision=String(body.decision) as DecisionChoice,reason=String(body.reason??"").trim(),expected=String(body.expectedAssessmentSummarySha256??"");if(!CHOICES.has(decision)||!reason||reason.length>config.decisionReasonMaxLength||!SHA.test(expected))throw new RuntimePublicError("invalid_decision_request","validation","The model-use decision request is invalid.",400);await initializeRuntimeRoot(config.runtimeRoot);const value=await recordDecision(config,assessmentId,decision,reason,expected,correlationId);const d=value.decision;const response:DecisionResponse={ok:true,decisionId:d.decisionId,assessmentId:d.assessmentId,decision:d.decision,selectedModelId:d.selectedModelId,selectedModelLabel:d.selectedModelId?modelLabel(d.selectedModelId):null,decisionScope:"one_run",operatorType:"trusted_internal_unverified",institutionalApproval:false,reason:d.reason,decisionStatus:d.decisionStatus,forecastAuthorized:d.forecastAuthorized,authorizationId:d.authorizationId,authorizationStatus:value.authorizationStatus,createdAt:d.createdAt,limitations:["Recommendation strength is not available.","This trusted internal decision authorizes at most one forecast and does not adopt a deployment model."],decisionCommitSha256:value.decisionCommitSha256};return Response.json(response,{status:201,headers:{"Cache-Control":"no-store"}});}catch(error){const failure=errorResponse(error,correlationId);return Response.json(failure.body,{status:failure.status,headers:{"Cache-Control":"no-store"}});}}
