import {createHash,randomUUID,timingSafeEqual} from "node:crypto";
import {readFile} from "node:fs/promises";
import {loadRuntimeConfig} from "@/lib/runtime/config";
import type {DegradationEvidenceJobRecord} from "@/lib/runtime/contracts";
import {errorResponse,RuntimePublicError} from "@/lib/runtime/errors";
import {loadModelDegradationPolicy} from "@/lib/runtime/model-degradation-policy";
import {readVerifiedModelDegradationEvidence} from "@/lib/runtime/model-degradation-store";
import {jobRecordPath,monitoringPaths,runtimeCollectionPaths} from "@/lib/runtime/paths";
import {readVerifiedMonitoringSummary} from "@/lib/runtime/outcome-store";
import {createPendingJob,initializeRuntimeRoot} from "@/lib/runtime/store";
export const runtime="nodejs";
const SHA=/^[a-f0-9]{64}$/;
function authorized(provided:string,configured:string){const a=createHash("sha256").update(provided).digest(),b=createHash("sha256").update(configured).digest();return configured.length>=16&&timingSafeEqual(a,b)}
export async function GET(request:Request):Promise<Response>{try{const config=loadRuntimeConfig(false),deploymentId=new URL(request.url).searchParams.get("deploymentId")??"dhaka_south";const value=await readVerifiedModelDegradationEvidence(config.repositoryRoot,config.runtimeRoot,deploymentId);return Response.json({ok:true,...value},{headers:{"Cache-Control":"no-store"}})}catch(error){const failure=errorResponse(error);return Response.json(failure.body,{status:failure.status,headers:{"Cache-Control":"no-store"}})}}
export async function POST(request:Request):Promise<Response>{const correlationId=randomUUID();try{const config=loadRuntimeConfig(false);if(!config.internalMonitoringEnabled)throw new RuntimePublicError("model_degradation_generation_disabled","validation","Model-degradation evidence generation is unavailable.",404);if(!authorized(request.headers.get("x-dengueops-internal-monitoring-secret")??"",config.internalMonitoringSecret))throw new RuntimePublicError("model_degradation_forbidden","validation","The monitoring credential is invalid.",403);
  const body=await request.json() as Record<string,unknown>,allowed=["deploymentId","evidenceOnlyAcknowledged","expectedIncludedOutcomeSetSha256","expectedMonitoringLatestSha256","expectedMonitoringSummarySha256"];if(!body||Array.isArray(body)||typeof body!=="object"||Object.keys(body).sort().join("|")!==allowed.sort().join("|")||body.deploymentId!=="dhaka_south"||body.evidenceOnlyAcknowledged!==true||!SHA.test(String(body.expectedMonitoringLatestSha256))||!SHA.test(String(body.expectedMonitoringSummarySha256))||!SHA.test(String(body.expectedIncludedOutcomeSetSha256)))throw new RuntimePublicError("invalid_model_degradation_request","validation","The evidence request does not satisfy the governed contract.",400);
  const policy=await loadModelDegradationPolicy(config.repositoryRoot);await initializeRuntimeRoot(config.runtimeRoot);const verified=await readVerifiedMonitoringSummary(config.runtimeRoot,"dhaka_south"),latestPath=monitoringPaths(config.runtimeRoot,"dhaka_south").latest,latestSha=createHash("sha256").update(await readFile(latestPath)).digest("hex");const pointer=verified.pointer as Record<string,unknown>;
  if(latestSha!==body.expectedMonitoringLatestSha256||pointer.monitoringSummarySha256!==body.expectedMonitoringSummarySha256||verified.summary.outcomeSetSha256!==body.expectedIncludedOutcomeSetSha256)throw new RuntimePublicError("stale_model_degradation_input","validation","The verified monitoring snapshot changed before job creation.",409);
  const jobId=randomUUID(),evidenceId=randomUUID(),createdAt=new Date().toISOString();const job:DegradationEvidenceJobRecord={schemaVersion:"1.0",jobKind:"degradation_evidence",jobId,evidenceId,deploymentId:"dhaka_south",geography:{level:"city",id:"BGD-DHAKA-SOUTH",name:"Dhaka South"},workflowMode:"degradation_evidence",policyId:policy.policy_id,policyVersion:policy.policy_version,policySha256:policy.policy_sha256,expectedMonitoringLatestSha256:String(body.expectedMonitoringLatestSha256),expectedMonitoringSummarySha256:String(body.expectedMonitoringSummarySha256),expectedIncludedOutcomeSetSha256:String(body.expectedIncludedOutcomeSetSha256),evidenceOnlyAcknowledged:true,status:"queued",progress:"queued",createdAt,claimedAt:null,startedAt:null,updatedAt:createdAt,completedAt:null,heartbeatAt:null,workerId:null,processId:null,timeoutSeconds:config.forecastOutcomeTimeoutSeconds,retryCount:0,error:null,committedEvidenceId:null};const paths=runtimeCollectionPaths(config.runtimeRoot);await createPendingJob(jobRecordPath(paths.pendingJobs,jobId),job);return Response.json({ok:true,evidenceId,jobId,status:"queued",statusUrl:`/api/runtime/jobs/${jobId}`},{status:202,headers:{"Cache-Control":"no-store"}});
}catch(error){const failure=errorResponse(error,correlationId);return Response.json(failure.body,{status:failure.status,headers:{"Cache-Control":"no-store"}})}}
