import { createHash, randomUUID, timingSafeEqual } from "node:crypto";
import { loadRuntimeConfig } from "@/lib/runtime/config";
import type { ForecastOutcomeJobRecord } from "@/lib/runtime/contracts";
import { errorResponse, RuntimePublicError } from "@/lib/runtime/errors";
import { jobRecordPath, runtimeCollectionPaths } from "@/lib/runtime/paths";
import { loadForecastOutcomePolicy } from "@/lib/runtime/outcome-policy";
import { createPendingJob, initializeRuntimeRoot } from "@/lib/runtime/store";
export const runtime="nodejs";
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i,SHA=/^[a-f0-9]{64}$/,PERIOD=/^[0-9]{4}-W[0-9]{2}$/,RECORD=/^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/,UTC=/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{1,6})?Z$/;
function canonical(value:unknown):string{if(Array.isArray(value))return `[${value.map(canonical).join(",")}]`;if(value&&typeof value==="object")return `{${Object.entries(value as Record<string,unknown>).sort(([a],[b])=>a<b?-1:a>b?1:0).map(([k,v])=>`${JSON.stringify(k)}:${canonical(v)}`).join(",")}}`;return JSON.stringify(value);}
function authorized(provided:string,configured:string){const a=createHash("sha256").update(provided).digest(),b=createHash("sha256").update(configured).digest();return configured.length>=16&&timingSafeEqual(a,b);}
export async function POST(request:Request):Promise<Response>{const correlationId=randomUUID();try{const config=loadRuntimeConfig(false);if(!config.internalMonitoringEnabled)throw new RuntimePublicError("forecast_outcome_monitoring_disabled","validation","Forecast outcome monitoring is unavailable.",404);if(!authorized(request.headers.get("x-dengueops-internal-monitoring-secret")??"",config.internalMonitoringSecret))throw new RuntimePublicError("forecast_outcome_forbidden","validation","The monitoring credential is invalid.",403);
  const body=await request.json() as Record<string,unknown>;const allowed=["deploymentId","expectedForecastCommitSha256","forecastHorizonWeeks","forecastRunId","forecastTargetPeriod","geography","limitationsAcknowledged","observationRecordedAt","observationRecordId","observationSourceId","observationSourceType","observedRaw","targetColumn"];if(!body||Array.isArray(body)||typeof body!=="object"||Object.keys(body).sort().join("|")!==allowed.sort().join("|"))throw new RuntimePublicError("invalid_forecast_observation","validation","The observation request contains unsupported or missing fields.",400);
  const geography=body.geography as Record<string,unknown>;if(!geography||Object.keys(geography).sort().join("|")!=="id|level|name"||geography.level!=="city"||geography.id!=="BGD-DHAKA-SOUTH"||geography.name!=="Dhaka South"||!UUID.test(String(body.forecastRunId))||!SHA.test(String(body.expectedForecastCommitSha256))||body.deploymentId!=="dhaka_south"||body.targetColumn!=="target_cases_next_2w"||body.forecastHorizonWeeks!==2||!PERIOD.test(String(body.forecastTargetPeriod))||!Number.isSafeInteger(body.observedRaw)||Number(body.observedRaw)<0||body.observationSourceType!=="synthetic_benchmark"||body.observationSourceId!=="dhaka_south_synthetic_benchmark"||!RECORD.test(String(body.observationRecordId))||typeof body.observationRecordedAt!=="string"||!UTC.test(String(body.observationRecordedAt))||!Number.isFinite(Date.parse(String(body.observationRecordedAt)))||body.limitationsAcknowledged!==true)throw new RuntimePublicError("invalid_forecast_observation","validation","The forecast observation does not satisfy the governed contract.",400);
  const policy=await loadForecastOutcomePolicy(config.repositoryRoot);if(policy.schema_version!=="2.0")throw new RuntimePublicError("forecast_outcome_policy_invalid","configuration","The active lifecycle-aware monitoring policy is unavailable.",503);await initializeRuntimeRoot(config.runtimeRoot);const jobId=randomUUID(),outcomeId=randomUUID(),createdAt=new Date().toISOString();const observation={deploymentId:"dhaka_south",geography:{level:"city",id:"BGD-DHAKA-SOUTH",name:"Dhaka South"},targetColumn:"target_cases_next_2w",forecastHorizonWeeks:2,forecastTargetPeriod:String(body.forecastTargetPeriod),observedRaw:Number(body.observedRaw),observationSourceType:"synthetic_benchmark",observationSourceId:"dhaka_south_synthetic_benchmark",observationRecordId:String(body.observationRecordId),observationRecordedAt:String(body.observationRecordedAt),limitationsAcknowledged:true} as const;const observationPayloadSha256=createHash("sha256").update(canonical(observation)).digest("hex");
  const job:ForecastOutcomeJobRecord={schemaVersion:"2.0",jobKind:"forecast_outcome",jobId,outcomeId,forecastRunId:String(body.forecastRunId),expectedForecastCommitSha256:String(body.expectedForecastCommitSha256),observationPayloadSha256,observation,operatorIdentifier:config.internalMonitoringOperatorId,deploymentId:"dhaka_south",workflowMode:"forecast_outcome_monitoring",policyId:policy.policy_id,policyVersion:policy.policy_version,policySha256:policy.policy_sha256,status:"queued",progress:"queued",createdAt,claimedAt:null,startedAt:null,updatedAt:createdAt,completedAt:null,heartbeatAt:null,workerId:null,processId:null,timeoutSeconds:config.forecastOutcomeTimeoutSeconds,retryCount:0,error:null,committedOutcomeId:null};const paths=runtimeCollectionPaths(config.runtimeRoot);await createPendingJob(jobRecordPath(paths.pendingJobs,jobId),job);return Response.json({ok:true,outcomeId,jobId,status:"queued",statusUrl:`/api/runtime/jobs/${jobId}`},{status:202,headers:{"Cache-Control":"no-store"}});
}catch(error){const failure=errorResponse(error,correlationId);return Response.json(failure.body,{status:failure.status,headers:{"Cache-Control":"no-store"}});}}
